XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXX X XXXXXXXXXBBBBBBBBXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XX XXXXXX XXXXXXXXXX XX
        XXXXXXXXXX XXXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXX
            X
        X
        
        XXXXXXXXXX XXXXXX X
            XXXX X
                XXXXXXXX XX
            X
            XX X
                XXXXXXXX XX
            X
        X
        
        XXXXXXXXXX XXXXXXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXX
            X
        X
        
        XXXXXXXXXX XXXXXXXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXX
            X
        X
        
        XXXXXXXXXX XXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXX
            X
        X
        
        XXXXXXXXXX XXXXXXX X
            XX X
                XXXXXXXXXXXXXXXXXXXX XXXXXXX XX
            X
            XXXX X
                XXXXXXXXXXXXXXXXXXXX XXXXXX XX
            X
        X
        
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XX XXXXXX XXXXXXXXXXX XX
        X X
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
            XXXXXXXXXXXXXXXXXXXX XXXXXX
        X
        
        XX XXXX XXXXX XXXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXX XXXX XXXXXXXXX
        X
    XXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X
                XXXXXXX X
                    XXXXXXXXXXX X
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBB
        XXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX

