BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXX
        XXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXX XXXX XXXXXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBBBBB
                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX
                    BBBB
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXX XXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX XXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXX
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX XXXXXX XXX XXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXX XXXXXXX XXXXXXXX
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            
            XXXX XXXXX XXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBB BBBBB BB BBBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBXXXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBB BBBBB BB BBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBXXXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXX XXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXX XXXX XXXXXXXXXXXXX X XXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            
            XXXX XXXX XXX
            XXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX
                    XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBB BBB BBBBBBBBBBBB
                    XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXX
                    XXXXXX
                    BBBBB
                    XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXFFFFFFF FF FFXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXFFFFFFFFFXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXX XXXXXXX
                XXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXX X XXX XXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXX X
            XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
X
XXXXXXXXX
BBBBBBBB

