BBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXX XXXXXXXXXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXX XX XXX XXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXX
        XXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXX

      XXXX XXXXX XXXXXXXXX XX XXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
                 X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
                 XXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXX XXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXX
                   XXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX
                 XXXX
          XXXXXX

          XXXX XXXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX
               XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                   XX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Fluentory AI Tutor') 
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Lesson-aware • Context-driven') 
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX
                 XXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 XX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Secure') 
            XXXXXX
          XXXXXX

          XXXX XXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXX

            XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX
                   XXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XX
                XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
                     XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Student') 
                XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   gettext(u'Can you explain this concept in simpler terms?') 
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX
                   XXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     XXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XX
                XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
                     XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Tutor') 
                XXXXXX

                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   gettext(u"Absolutely. Let's break it down step by step using an example from your lesson.") 
                XXXXXX

                XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX
                  XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Give an example') 
                  XXXXXXX
                  XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Quiz me') 
                  XXXXXXX
                  XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Translate') 
                  XXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX

          XXXXXX

          XXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXX
               XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXXX
                 XXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
                 XX
              XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Ask anything about this lesson…') 
              XXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX

        XXXXXX
      XXXXXX

      XXXX XXXXXX XXXXXXXXX XXXX XXX
      XXXXX

        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'AI Tutor Inside Every Lesson') 
        XXXXXX

        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Your Tutor.') XXX XX gettext(u'Always There.') 
        XXXXX

        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
           XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Students never get stuck. Every question is answered in context, explained clearly, and aligned with their exact lesson.') 
        XXXX

        XXX XXXXXXXXXXXXXXXX XXXXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Explains concepts in plain language') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Responds using the active lesson') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Reinforces learning through quizzes') XXXXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Supports multiple languages') XXXXX
        XXXXX

        XX XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Try a Sample Question') 
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX

      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX
