BBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXX XX XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXX
        XXXX
    XXXXXX
  XXXXXX

  XXXX XXXX XXXXXXX XXXXX XXX XXXXX X XXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXX

      XXXX XXXXX XXXXX X XXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Trust & Verification') 
        XXXXXX

        XXXX XXXXXXXX XXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Verified Certificates.') XXX XX
           gettext(u'Employer-Ready Proof.') 
        XXXXX

        XXXX XXXX XXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
           XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Every Fluentory certificate is uniquely issued, QR-verifiable, and backed by a tamper-resistant verification record.') 
        XXXX

        XXXX XXXXXXXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
                 X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
                 XXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXXX XXXXXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXX
                   XXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX
                 XXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX

            XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Verify Certificate') 
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXX gettext(u'Certificate ID (e.g., FLU-2026-0X92A)') X
                XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
                X XX

              XXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXX
                  XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXX
                XX
                 gettext(u'Verify') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
              XXXXXXXXX
            XXXXXX

            XX XXXXXXXXXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Verification confirms issuance, completion status, and authenticity.') 
            XXXX
          XXXXXX
        XXXXXX

        XXXX XXXXX XXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'QR Verified') 
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Employer-Ready') 
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Fraud-Resistant') 
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXX XXXXXXXXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX
                 X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
                 XXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXXXXX XXXXXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Certificate Preview') 
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'QR Verified') 
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXX XXXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
               XXXXXXX
                 XXXXXXXXXXX
                   XXXXXXXXXXXXXXXX
                     XX XXXXXX XXXXXX
                     XXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXX
                   XX
                 XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
               XX

            XXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX
                  XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Certificate of Completion') 
                  XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXX
                     XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Certificate ID') 
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXX XXXX
                     XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Issued') 
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Instantly after completion') 
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX

          XX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
             XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Preview only. Actual certificates include live QR verification.') 
          XXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX
