BBBB BBBB
XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXX XX XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXX
        XXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXX XXXXX XXX XXXXX X XXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'FAQ') 
      XXXXXX

      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Questions, Answered Clearly.') 
      XXXXX

      XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Straight answers to the most important questions learners, parents, and employers ask.') 
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXX XXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

        XXXX XXX XXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXX gettext(u'How does the placement test work?') X
             XXXXXXXXXXXXXXXXXX gettext(u'The test adapts to your answers in real time and recommends the best starting point so you do not repeat what you already know.') X
             XXXXXXXXXXX gettext(u'5–10 minutes') X gettext(u'Adaptive') X gettext(u'Instant results') X
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'How does the placement test work?') 
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Quick, adaptive, accurate') 
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'The placement test evaluates your level using adaptive questions, then recommends the ideal course so you learn efficiently from day one.') 
          XXXXXX
        XXXXXX

        XXXX XXXX XXXX XXXXX XXX XXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXX gettext(u'Are certificates internationally recognized?') X
             XXXXXXXXXXXXXXXXXX gettext(u'All certificates are QR-verifiable and shareable with employers or institutions worldwide.') X
             XXXXXXXXXXX gettext(u'QR verified') X gettext(u'Global') X gettext(u'Employer-ready') X
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX

          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Are certificates internationally recognized?') 
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Verifiable worldwide') 
                XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Yes. Every certificate includes QR verification and a permanent record that employers can instantly validate.') 
          XXXXXX
        XXXXXX

      XXXXXX

      XXXX XXXXXX XXXXXX XXXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Selected question') 
          XXXXXX

          XXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'How does the placement test work?') 
          XXXXX

          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
             XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'The test adapts to your answers in real time and recommends the best starting point.') 
          XXXX

          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'5–10 minutes') 
            XXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Adaptive') 
            XXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Instant results') 
            XXXXXXX
          XXXXXX

          XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBBBX
             XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Take the Placement Test') 
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
    XXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXX
        XXX
  
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXXX
  
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
  
        XXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
          XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX X XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
        XXX
      XXX
    XXX
  
    XX XXXX XXXXX XXX XX XXXXXXX
    XXXXXXXXXXXXXXXXX
  XXX
  XXXXXXXXX
  