BBBB BBBB
XXXXXXXX XXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXXX XXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXX XX XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXX
        XXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX

      XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Featured Programs') 
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
           XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Curated learning paths designed for measurable outcomes and real-world impact.') 
        XXXX
      XXXXXX

      XXXX XXXXXX XXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXX
          XX
           gettext(u'All Programs') 
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Beginner') 
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Intermediate') 
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Advanced') 
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Business') 
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Language') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX

      XXXX XXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
             gettext(u'30-sec Preview') 
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Introduction to Data Science') 
            XXXXX
            XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'Beginner') 
            XXXXXXX
          XXXXXX

          XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
             XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Master the foundations of data analysis, visualization, and decision-making.') 
          XXXX

          XXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'40 hrs') XXXXXXX
            XXXXXX gettext(u'Preview Included') XXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX
               XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'View Program')  XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXX XXXX XXXXXXXXX XXXXX XXX XXX XXXXX XXXXXXX XXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
      XXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXX
      X
    
      XXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
          XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX
    
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X XXXXXXXX
          XXXXXXXXXXXXXXXXXXX X XX XXXX XXXX XXXXXXXXXXXXXXXXXXXXX
    
          XXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    
            XXXXX XXXX X
              XXXXXX XXX XXXXX XX
              XXXXXX XXX XXXXX XX
              XXXXXX XXX XXXXXXXXX
    
            XXXXXXXXXXXXXXXXXX X XXXX X XXXXXXX X XXXXXXX
          XXX
        XXX
      XXX
    XXX
    XXXXXXXXX
    