BBBB BBBB
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXX XXXX XXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXX XXXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXX

          XXXX XXXXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'AI-Powered Learning Paths') XXXXXXX
          XXXXXX

          XXXX XXXXXXXX XXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'The Modern Way') XXX XXXXXXXXXXXXX XXXXXXXXX XX
             gettext(u'To Learn Globally.') 
          XXXXX

          XXXX XXXXXXXXXXX XXX
          XX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Placement-based learning. Milestone quizzes. Verified certification. Built for outcomes.') 
          XXXX

          XXXX XXXXXXX XXX XXX
          XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XX
              XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBBBX
              XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            X
               gettext(u'Take the Free Placement Test') 
              XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXX XXX XXX
            XX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
            X
               gettext(u'Browse Courses') 
            XXXX
          XXXXXX

          XXXX XXXXX XXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX gettext(u'Secure Payments') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX gettext(u'Verified Certificates') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX gettext(u'Multi-language Support') XXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXXX XXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Lessons Completed') XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Average Satisfaction') XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Countries') XXXXXX
            XXXXXX
          XXXXXX

        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
