XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXX XXXXXXX X XXXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXX
     XXXXX XXXXX
       X XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
       X XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXX XXXX XXXXXXXXX XX XXXXXX XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

  XX XXXXX XXXXXXXXX XXXXXXXXX X XXXXXXXX XXXXXXXX XX
  XXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXX XXXXXXX XXX XXX XXXXXX   XX XXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX     XX XXXXX XXXXX XX
    XXXXXXXXXXXXX XXXXXXX XXX XXX XXXXXX      XX XXXX XXXXX XX

    XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  X

  XX XXXXX XXXX X XXXXX XXXXXXX XXXXXX XXXXX XXXXXXXX XXXX XXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  X

  XX XXXX XXXX XXXXXXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXX XXXXXX X
    XX XXXX XXXXXXXX XXXXX XX
  X

  XX XXXXXX XXXXXX XX
  XXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXX XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXX XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XXXXXX XXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XX XXXXX XXXXX XXXXXXX XXXXXXXXXXX XX XXXX XXX XXXX XXX XXXXX XXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXX XXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X

  XX XXXX XXXXX XX
  XXXXXX XXXXXXXXXXX X
    XXXXXXX XXXXXXXXXXXX
    XXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXX XXXXXXXXXXX X
    XXXXXXXX XXXXX XX XXXX XXXX XX XXXXX XX
    XXXXXXX XXXXXXXXXXXX
  X
XXXXXXXX

BBBB BBBB
XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XX
    XXXXXX
  XXXXXX

  XXXX XXXX XXXX XXXXX XXXXXXX X XXXXXXX XX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXX XXXXXXX XXXXXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXXXXXX
          XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
          XX
          XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Proof of Learning') 
          XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            X  gettext(u'placement')  X  gettext(u'milestones')  X  gettext(u'verification') 
          XXXXXXX
        XXXXXX

        XXXX XXXXXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Not more courses.') XXXXXXXXXX XX
          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Better outcomes.') XXXXXXX
        XXXXX

        XXXX XXXXXXXXXXX XXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Fluentory places you correctly, keeps you moving with checkpoints, and certifies you with proof that can be verified. No fluff. No \\') 
        XXXX

        XXXX XXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXX XXXXX XXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Outcome System') 
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Live progress tracking') 
            XXXXXX
          XXXXXX

          XXXX XXXXX XXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'01 Start at the right level') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'AI placement removes repetition and guesswork.') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'02 Advance with milestones') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Quizzes verify understanding before moving on.') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'03 Graduate with proof') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'QR + Certificate ID verification for employers.') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXX XXX XXX XXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXX
              XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Take the Placement Test') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX

              XX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Verify a Certificate') 
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXX XXXXX XXXXX XXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX

        XXXX XXXX X XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'AI Placement Test') XXXXX
                  XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Fast assessment + course recommendation tailored to your level.') 
                  XXXX
                XXXXXX
              XXXXXX

              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Placement') 
              XXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Time') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'5–10 min') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Result') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Instant') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fit') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Accurate') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'See example') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Eliminates wasted time') 
              XXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXX X XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Milestone Quizzes') XXXXX
                  XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Checkpoints tied to lessons so progress is real—not assumed.') 
                  XXXX
                XXXXXX
              XXXXXX

              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Milestones') 
              XXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Format') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Lesson-tied') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Goal') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Mastery') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Path') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Structured') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'See example') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Prevents drop-off') 
              XXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXX X XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'QR Verified Certificates') XXXXX
                  XX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Share proof that employers can verify instantly—no screenshots needed.') 
                  XXXX
                XXXXXX
              XXXXXX

              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Proof') 
              XXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Verify') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'QR + ID') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Status') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Tamper-safe') XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Share') XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Global') XXXXXX
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'See example') 
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Employer-ready') 
              XXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXXX
