BBBB BBBB
XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
    XXXXXXXXX
XXXXXXX



