XXXX XXXXXXX XXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXX XXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            
            XXXX XXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                
                XXXX XXXXX XXXXX XXX XXXXXX XXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                    XXXXXX 
                        XXXXXXXXXXX 
                        XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    X
                XXXXXX
                
                XXXX XXXXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXX XXXXX XXXXXX
XXXXX XXXXXXXXXXXXXX X X
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXX XXXXX
    
    XXXXXX X
        XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXX XX XXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXX
            X
        XXX
    XX
    
    XXXXXXXXXX XXXXXXXX XXXXXXX X XXX X
        XXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXX XX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXXXX
            
            XXXXX XXXXX X XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXX XX XXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
            
            XX XXX XXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XX XXX XXXX
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXX X XXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXX XXXXX XXX XXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXX XXX XXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XX XXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XX XXXXXXXXX XXXXXX XXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXX XXX XXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XX XXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXX XXXXX XXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            
            XX XXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXX
        XXX
    XX
    
    XXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXX XXXX X XXXXXX XXXXX XXXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX
            XX XXXXXXX XX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX
                XXXXXXX
            X
            XXXXXXXXXXXXXXXXXX
        X XXXX X
            XX XXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX
        X
    XX
    
    XXXXXXXXXXX X XXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXX
        X
        
        XX XXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
        XX XXXXX
    XX
    
    XXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X
            XXXX XXXXXXXX 
            XXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
            XXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXX XXXXXX XXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXXXXXXXXX
        X
    XX
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X
            XXXX XXXXXXXX 
            XXXX XXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXX XXXXXX XXXX XXXXXXXXX
            XXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXX
        X
    XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X
            XXXX XXXXXXXX
                XXXXXX X
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX
            XXXX XXXXXXXXXX
                XXXXXX X
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XX
            XXXX XXXXXXXXXX
                XXXXXX X
                    XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XX
            XXXXXXXX
                XXXXXX X
                    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XX
        X
    X
XX

XX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXX
XXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXX XXXXXXX X XXX X
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXX XXX
    XXXXXX XXXXX
XX

XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXX XXXXXXX X XXX X
    XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX
    XXXXXX XXXXXX XXX XXXXX
XX

XXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX X XXX XXXXXXX X XXX X
    XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXX XXX
    XXXXXX XXXXXX XX XXXXX
XX

XX XXXXXX XXX XXXX XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X XXX X
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXX XXX
    XX XXXXXXXXXX XXX XXXXX X
        XXXXXXXXXXXXXX
    X
    XXXXXX XXXXXX
XX

XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXX XXX XXXXX X
                XXXXXXXXXXXXXX
            X
        XXX
    XXX
    
    XX XXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXX XXX XXXXX X
                XX XXXXXXXXXXXXXXXX XXX XXXXXXXX XX XXXXXXXXXXXX XXX XXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX XX XXXXXXXXXXXXXXXX XXX XXXX X
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                X XXXX XX XXXXXXXXXXXXXXXX XXX XXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X
        XXX
    XXX
    
    XX XXXX XXX XXXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XXXXX XXXXXXX X XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXX XXXXX X
                        XXXXXXXXXXXXXX
                    X
                XXX
            X
        X
    XXX
    
    XX XXXX XXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XXXXX XXXXXXX X XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
                    XX XXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXXXXXX XXX XXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XX XXXXXXXXXX XXX XXXXX X
                            XX XXXXXXXXXXXXXXXX XXX XXXX X
                                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
                            X XXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            X
                        X
                    X
                XXX
            X
        X
    XXX
XXX

XX XXXXXXXXXX XX XXX XXXXX
XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXX
X XXXX X
    XXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX

XXXXXXX
XX XXXXXX XXXXX XXXXXXXXXX XX
XXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXX XXXX XXXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
X

XXXXXXXXXX XXXXXX X
    XXXX X XXXXXXXX XX X
    XX X XXXXXXXX XX X
X

XXXXXXXXXX XXXXXXX X
    XXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXX XX
    X
    XX X
        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXX XX
    X
X

XX XXXXX XXXXXX XX
XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXX
X
XXXXXXXX

