BBBB BBBB
XXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXX
        XX XXXX XXXXXXXXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX XXXXX
        X
        XX XXXX XXXXXXXXXX XX XXXX XXXX XXXXX XXXXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXX XXXXX
            XXXXXXXX XX
        X
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXX XXXXXXXXX X XXXX XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX
            XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX
                XXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXX 
                    XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXX XXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXX
                XX
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXX X XXXXXXXX XXX
        XXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX
            XX XXXXXXBBB BBBBBBXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXXXX gettext(u'Courses') XXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXXXX gettext(u'Outcomes') XXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXXXX gettext(u'Proof') XXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXXXX gettext(u'Pricing') XXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        
        XXXX XXXXX XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXX XXXXXX XXXX XXXXXXXX XX XXXXXXXXX XXXXXX XXXXXX XX XXXX XXX XXXXXX XXXXX XXX XXXXXXX XXXXXXXXXX XXX
             #

            BB BBB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX gettext(u'Switch View') XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Admin') XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Student') XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Teacher') XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Partner') XXXX
                XXXXXX
            XXXXXX
            BBBBB
            XX XXXXXXBBB BBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX gettext(u'Login') XXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Take Placement Test') XXXX
        XXXXXX
    XXXXXX
XXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXX XX XXXXXX XXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXXX XXXXXX
    XX XXXXX XX XXXXXX XXXXXXX

    XXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX
        XX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX
    XXX

    XX XXXXXXX XXXXXX XXXXXX XXX XXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX

    XX XXXXX XX XXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX

    XX XXXXX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXX XXX
XXX
XXXXXXXXX
