BBBB BBBB
XXXXXXXX XXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
          XXXXXXX XX XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXX
        XXXX
    XXXXXX
  XXXXXX

  XXXX XXXX XXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXX

    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX
         gettext(u'Pricing') 
      XXXXXX

      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Simple. Global. Confident.') 
      XXXXX

      XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Choose a plan that fits your pace. Upgrade anytime — your progress always stays with you.') 
      XXXX

      XXXX XXXXXXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
          XXX
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX

      XXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
           XX

        XXXX XXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Starter') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'For casual learners') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Billed monthly') 
          XXXXXX
        XXXXXX

        XXX XXXXXXXXXXXXXXXX XXXXXXX
          XXXXX  gettext(u'Access to all courses') XXXXX
          XXXXX  gettext(u'AI Tutor support') XXXXX
          XXXXX  gettext(u'Progress tracking') XXXXX
          XXXXX  gettext(u'Community access') XXXXX
        XXXXX

        XX XXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Get Started') 
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXX XXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
             gettext(u'Most Popular') 
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
             XXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX X XXXX XXXXX XXXXXXXXXXXXXXXXXXX
             XX

          XXXX XXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Professional') XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'For serious learners') XXXX
          XXXXXX

          XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Includes certificates') 
            XXXXXX
          XXXXXX

          XXX XXXXXXXXXXXXXXXX XXXXXXX
            XXXXX  gettext(u'Everything in Starter') XXXXX
            XXXXX  gettext(u'Verified certificates') XXXXX
            XXXXX  gettext(u'Priority support') XXXXX
            XXXXX  gettext(u'Advanced analytics') XXXXX
          XXXXX

          XX XXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Get Started') 
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX

          XXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            X  gettext(u'Gift a course available') 
          XXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
           XX

        XXXX XXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Enterprise') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'For teams & institutions') XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Custom') XXXXXX
          XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Talk to sales') 
          XXXXXX
        XXXXXX

        XXX XXXXXXXXXXXXXXXX XXXXXXX
          XXXXX  gettext(u'Everything in Professional') XXXXX
          XXXXX  gettext(u'Team management') XXXXX
          XXXXX  gettext(u'Custom learning paths') XXXXX
          XXXXX  gettext(u'Dedicated support') XXXXX
        XXXXX

        XX XXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Contact Sales') 
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX
      XXXXXX

    XXXXXX

    XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      X  gettext(u'Cancel anytime · Keep your progress') 
    XXXXXX

  XXXXXX
XXXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X X XXXX XXXX XXXX XXXX XXXX XXX XX
  
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXX XX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXX
      XXX
  
      XXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXX
      XXX
  
      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XX XXXX XXXX XXXXXXXXXXXXXXXXXXXXX
      X
  
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    X
  
    XXXXXXXXXXXXXXXXXXX XX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
  
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
  XXX
  XXXXXXXXX
  