XXXXXXX
    XX XXXXX XXX XXXXXXXXX X XXXXXX XXXXXX XX XXXXX XX
    XXXXX X
        XX XXXX XXXX XXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXXXXXX XXXXXXXX XXX XXXX XXXX XX
        XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXX XXX XXXXXXX XXXXXXXXXXX XXX XXXX XXXX XX
        XXXXXXXXXXXX XXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXX XXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX XXX XXX XXXXX
        
        XX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXX XXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XX XXXXX XXXX XXXXXX X XXXXXXX XXXXX XXXX XXXXXXXXX XXXXX X XXXXX XX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXXXXXX XXXXXXXX XXX XXXXX XXXX X XXXXXXX XXXX XXXXXX XXXXXXXXX XXX XXXX XX
        XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXX XXX XXXXXXX XXXXXXXXXXX XXX XXXXX XXXX X XXXXX XXXXX XX
        XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        
        XX XXXXXXX XXXXXXX XXX XXXXX XXXX X XXXXX XXXXX XXXXXXXX XX
        XXXXXXXXXXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXX XXXX XXXXXXXX XXX XXX XXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXX XXXX XXXXXXXX XXX XXX XXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX
        
        XX XXXXXXX XXXX XXXXXXXXX XXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXXX XXXXX XXXXXX XX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX
        
        XX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX XXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXXX XXX XXXX XXXX XX
    XXXXX X
        XXXXXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX X XXX XXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX X XXX XXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    X
    
    XX XXXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXX X XXXXXXX XXXXXX XX
    X X
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
    X
    
    XX XXXX XXXXXXXXX XXXXXX X XXXX XXXX XX
    XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXX XXXXXXXXX XXXXXX X XXXXX XXXX XXXXXXX XXXXX X XX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    
    XX XXXXX XXXXXX X XXXX XXXX XX
    XXXXXXX X
        XXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXXXXXX XXXX
    X
    
    XX XXXXX XXXXXX X XXXXX XXXX XXXXXXX XXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXXX XXXX
    X
    
    XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX
    XXX XXX XXX XXX XXX XX X
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXX
    X
    
    XX XXXXXXXXXXX XXXX XXXXX XXXXXXXXX XXX XXXXXXXX XXXXXXX X XXXXXX XXX XX
    XX XXXXXXXX XXXXXXXXXX XXX XXXXXXXX XX XXXXX XXXX X XXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXX XXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXX XXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXX
    X
    
    XX XXXXXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXX XXXXXX XXXX XXXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXX
        X
        XX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXX
        X
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXXX XX
        XXXX XXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXX XXX XX
        XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XX XXXXXXX XXXXXXXXXX XXXXXXXXX XX
    XX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX X XXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XX
    XX XXXXXXXX XXXXXX XX XXXXX XXXX XXX XXXXXXXXX XXXXXXX X XXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXX XX XXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXXX XXXX X XXXX XXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXX XXXX XXXXXXXXXXX XX XXXXXXXX XXX XXXX XXXX X XXXX XXXXX XX
    X
    
    XX XXXXXXXX XXXXXX XXXXXXXXX XXXXX XXX XXXXXXXXX XXXXXXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXX XX XXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXXX XXXX X XXXXXX XXXXXXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXX XXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXX XXXX X XXXXXXX XXXX XX
    X
    
    XX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXX XXXXXXXXXXX
    X
    
    XX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXXXXXXXXX XXX XXXX XXXXXXXX XXXX XX XXXXXXXXXXX XX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXX XXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXX
    X
    
    XX XXXXXXX XXXXXX XXXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXX
        XXXXXXXX XXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXX
    X
    
    XX XXXXXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XX XXXX XXXX XXXXXXXXX XX
    XXXXXXXXXX XXXXXXXX X
        XXXX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        XX X
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XX XXXX XXXXXXX X XXXXXXX XXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X
    
    XX XXXXXXX XXXXXXXXX X XXXXXX XXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
        XXXXXXXX XXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXX XXXXX XXXX XXXXXXX X XXXXXX
       XXXXXXX XX XXXXXX XXXXXXXX XXXXXXXX XXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XX XXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX X XXXXXX XXXXXXXXX XXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    X
    
    XX XXXXXXX XXXX XXXX XXXXXXX X XXXXX XXXX X XXXX XXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        XXXXXXXXX XXXXXXX
    X
    
    XX XXXX XXXXXX XXXX XX XXX XX XXXXX X XXXXXXX XXXXXXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXX XX
        XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXX XXXX XXXXXXXXX XXXXXXXX XX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXXX
    X
    
    XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXX XXXXXXX XXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXX XXXXX XXX XXXXXX XXXX X XXXXXX XXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXX XX
    X
    
    XX XXXXXXX XXXX XXXXX X XXXXX XXXX X XXXX XXXX XXXXX XXXXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXX XXX XXXXXX XXXXXXXX XX XXXXX XXXX XX
    X
    
    XX XXXXXXX XXXXXX XXXX XXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXX X XXXXX XXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX XX XXXXX XXXX XXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXX XXXX XXXXXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXX XXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXX XXXXXXX X XXXXX XXXX X XXXXX XXXXXXX XXXXX XXXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXX XXXXXXX XXXXXXX XXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXXXXXX X XXXXXX XXXXX XXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXX XXXXXXX X XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXXX X XXXXX XXXX X XXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXX XXXX XXXXXXXX XXX X XXXXX XXXX
       XXXX XXX XXXX XXXXXX XXXXX XXXXXXXX XX XXXXX XXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XX XXXX XXXXX X XXXXX X XXXXXXXXXXX XXXXXXXX XXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX XX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXX X XXXXXXX X XXXXXXXXXXX XXXXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXX XXXX X XXXXXXXXXXXX X XXXXXX XXXXX XXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XX XXXXXX XXXX XX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXX XXXX XXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
    X
    
    XX XXX XXXXXXXXXXXXX XXXX XXXX X XXXXXX XXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXX XXX XXXXXXXXXXX
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX X XXXXXX XXXX XXXXX XXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXX XXX XXXXXX XXXXXXXX XX
    X
    
    XX XXXXXX X XXXXXX XXXX XXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX XX XXXX XXXXXXXX XXXX XX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXXXXX XXXXXX XXXXX XXX XXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXX XXXXXXX
    X
    
    XX XXXXXX XXXXXX XXXXX XXXX XXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX
        XXXXXXXXX XXXXXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XX
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXX XX
    X
    
    XX XXXXXXXX XXX XXXXXXX XXXXXXX XX XXXXXX XXXXXX X XXX XXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXX XXXX XXXXXXX XX XXXXXXXXXX XXXXX XXXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X X X
        XXXXXXXXX XXXXXXXXX
        XXXXXXXX XX
    X
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXX XXXXXXXXX XXXX XXXX XXXXX
       XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXX XXXX XXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XX XXXX XXXXX XXXXX XXXX XXXXXXXX XXXXX X XXX XXXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXX XXXX XXXXXX XXXXXXX XXXXX X XXXXXXXX XXXXXXXXX XXXX XXXXXX XXXX XXXXX XXXXXXXXX XX
    XX XXXXXX XX XXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXX XX XXXXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXX XXXX XXXXXXXX XX XXXXX X XXXXXXXXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXX XXXXXXXX XXXXXX XXX XXX X XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX XX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXX XXXX X XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXX XXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXXX XXXXX X XXXX XXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXXXX XXXXXXX X XXXXXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXX X XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXX XXXXX XXX XXXXX XXXXXXXX X XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX X X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXX XXX
    XXXXXXXXXXXXXXXXXXX XXXXX XX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXX XXXX XXXXXX XXX XXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXX XXXXXXXXXX XXXXXXXXX
       XXXX XXXXXX XXXXXX XXXXXXXX XXX XXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XX XXXX XXXXX XXXX X XXXX XXXX XXXXXXX XX
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX XX XXXXXXXX XX
        XXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXX XX XXXX XX XXXXXXXXX XXX XXXXX XXXX XX
        XXXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX XX XXXXXXXX XX
        X
    X
    
    XXXXXX XXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXX XX XXXXXXXX XX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXX XXXXXXX XXX XXXXX XX XXXXXXXX XXX XXXX XXXX XX
    X
    
    XX XXXX XXXXXXXX X XXXXXXXXX XXXXXXX XXXX XX
    XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXX XX XXXXXXXXX XX
        XXXXXXXXXXXX XXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXX XX XXXXX XX XXXXXXXXX XXX XXXXX XXXX XX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXX XX XXXXXXX XX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXX XXXXX XX XXXXXXXXX XXX XXXX XXXX XX
    X
    
    XX XXXX XXXXX X XXXXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX XX XXXXXXX XX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXX XX XXXX XX XXXXXXXXX XXX XXXXX XXXX XX
        XXXXXXXXXXXXXX XXXXXXX
    X
    
    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX XX XXXXXXXX XX
        X
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXX XXXXXXX XXX XXXXX XX XXXXX XXX XXXX XXXX XX
    X
    
    XX XXXX XXXXXXXXXXX X XXXXX XXXX XXXX XX XXXXX XX
    XXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX XX XXXXXXX XX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXX XX XXXXX XX XXXXXXXXX XXX XXXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXXXXXX XXX XXXX XXXX XX
    X
    
    XX XXX XXXXX X XXXXXXX XXXXXXXXXX XXXXX XX
    XXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX XX XXXXXXX XX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXX XXXXXXXX XXX XXX XXXXXX XX XXXXXXXXXXXXXXXX XX XXXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXXXXXXXXXXXXXX XX XXXX XXXX XX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXX XXXXX XXXXXX XXXX X XXXXX XXXX XXXXX
       XXX XXXX XXXX XXXXXXXX XX XXXXX XXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    
    XX XXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXX XXXXXX X XXXXX XXXXXXXXXX XXXX XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXX XXXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXX XXX XXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXXXXXX XXXXXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXXX XXXX X XXXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX X XXXXXX XXXX XXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX X XXXXX XXXXXXXXXX XXXX XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXX XXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXX XXXXXXX XXXXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXX XXXXXXX X XXXX XXXX XX XXXXX XXXX XX
    XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
XXXXXXXX

