XXXXXXXX
XXX
 X XXXXX XXXXXX XXXXXX
 X XXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXX XXX XXXXX
 X XXXXXXXX XXXX XXXX XXX XXX XXXXXXXXXXXXX
 XX

XXXXXXXXXXX X
    XXXX XXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXX

    XXX
     X XXXXXX XXXXXX XXXXXXXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXX
        X
        XXXXXX XXXXXXXXXXX
    X

    XXX
     X XXX XXXXXXX XXXXX XXXX XXXXXXXXXXXX XX XXXXXXX XX XXXXXX XXXXXXXXXXX XXXXXXXX XX XXXX
     XX
    XXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXX XXX XXXXXXXXXXX XX XXXXXX XXX XXXXXXXXXXX X
            XXXXXX XXXXXXX
        X
        XX XX XXXXXX XXXXXXXXXX X XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XX XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    X

    XXX
     X XXXX XXXXX XXXXXXXXXX XX XXXXXXXXXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    X

    XXX
     X XXXXX XXXXX XX XXXXXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX X XXXXXXXXXXXXXX
        
        XX XXXXXX XXXX XXXXX XXXXXXX XXXXX XXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        
        XX XXXX XXXXXXXXXX XXXX XX XX XXXXXX
        XX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XX XXXXXX XXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
        
        XX XXXXXX XXXXXX XXXXXX XXXXX XXXXX XX XXX XX XXXXXX
        XX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXX
     X XXXXXX XXXXXX XXXXXX XXXXX XXXXX XX XXXXXXX XXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXX XX XXXXXXXXX X
            XX XXXXXX XXX XXXXXXXXXXX X
                XX XXXX XXX XXXX XXX XXXXXX XX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXX XXXXXXX
                X
            X XXXX X
                XX XXXX XXXX XXXX XXX XXXXXX XX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXX XXXXXXX
                X
            X
        X
    X

    XXX
     X XXXXXX XXXXXXX XXXXX XXX XXXX XXXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXX XXX XXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
    X

    XXX
     X XXXXXXXXXX XXXXX XX XXXX XXXX
     XX
    XXXXXXXX XXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
    X

    XXX
     X XXX XX XXXXX XXXXXXXXX
     XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXX XXXXXX XXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        X

        XX XXXXXX XXX XXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXX XXX XXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXX X XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
            X
        XXX

        XX XXXXXX XXX XXXXXX XXXXXXXXXX XXXXXXX XXXXX XX XXXX XXXXXX XXX X XXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XX XXXX XXXXX XXXXXX XXXXXXXXXX XX XXXX XXXXXX XXX X XXXXXX XXXXXXXXXX
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX X
                    XXXXX XXXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        X
    X

    XXX
     X XXXXXXXXXX XXXX XXX XX XXXXX
     XX
    XXXXXXXX XXXXXX X
        XX XXXXX XXXXX XXXXXXXXXXX XX XXXXXXX XXXXX XXXXXXX XXX XXXXXX
        XX XXXX XXXX XXXXXXXXXX XX XXXX XXXXXXX XXXXX XXXXX XXX XXXXX XXXX
        XXXXXXXXXXXX
        
        XX XXX XX XXXXX XXXXXXXXX XXXX XXX XX XXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XX XXXXXXXX XXXXX XXX XXXX XXXX XXXXXX XXX XXX XXXX XXXXXXXX
                XXXXX XXXXX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        X XXXX X
            XX XXX XXXXXXX XXXXX X XXXX XXXXXXX XX XXXXXXXXXX XXXX XXX XXXX XXXXXXX
            XXXXX XXXXX X XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXX XX XXXXX XX XXXXXXX XXXXXX
    XXXXXXX

    XX XXXXXX XXX XXXXXXXX XXX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXX XXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXX X
            XX XXXXXX XXX XXXXXXXXXXX XX XXXXX XXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
            X
        XX
        XXXXXXXXX XXXXXXXX
    XX
XXXXX
XXXXXXXXX


