BBBB BBBB
XXXX XXXXX XXX XXXXXXXX XXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
  X
X
  XXXX XXXX XXXXXXXXX XXXXX XXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX
    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXX
        XXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
        X
      X
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        X
           gettext(u'Trusted by learners worldwide') 
        XXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
        X
           gettext(u'Partners') 
        XXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXXX
      X
    X
      XXXX XXXX XXXXX XXXXX XX XXXX XXXXX XX XXXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXX XXXXXX XXXXX XXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXX
        X
          XXXX XXX X XXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXX XX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXX XX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXX XX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXX XX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXX XX
          XXXXXX

          XXXX XXX X XXXXXXXXXX XXX XXXXXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXX XXXXXXXXX XXXXX XX XXXX XXXXXXXX XX XXX XXXXXXX XXX XXXXX XXXXXXX XXX
  XXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX X
      XX X XXXXXXXXXX XXXXXXXXXXXXXX X
      XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
    X
  XXXXXXXX
XXXXXXXXXX
