XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXX X
                XXXXXXX X
                    XXXXXXXXXXX X
                        XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    XX
                    XXXXXXX X
                        XXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        XXXX XXXX X XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
            XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXXXXXXX XXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                
            XXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        
        XXXX XXXXX XXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXX XXXXXXXX XXXXX XXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                        XXXXXXXX
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXX XXXXX XXX
                XXXXX
                    XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                        XXXXXXXX
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        
                        XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                
                XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXX XXXXXXXXX
                    XXXX
                XXXXXX
                
                XXXX XXXX XX XXXXXX XXX
                XXXXXXX 
                    XXXXXXXXXXXXX 
                    XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                X
                    XXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXXX
            
            XXXX XXXX XX XXXX XXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXX XX XXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XX XXXX
                    XXXX
                XXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXX XX XXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXX
            XXXX
        XXXXXX
    XXXXXX
    
    XXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX XXXX XXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXX
            XXXXXXXXXXXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXXX

