XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXX X XXXXXXXBBBBBBBBXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXX X
                XXXXXXX X
                    XXXXXXX X
                        XXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXBBBBBX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
            BB BBBBBBBB
                BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXX XXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXX XXXXX XXXXXX XXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXX XXXXXXXXXBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBBX
                        
                    XXXXXX
                BBBBBB
            BBBBB
            
            BBBBB BBBBBBBBBBBBBBB
        XXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX

