BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XX XXXXXXX X XXXXXXXX
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXBBBBXXXXXX XXXX XXXXXXX XXXXXXX XXX XXXXX XXXXX XXXXXXXXBBBBB
        XXXX
    XXXXXX
    
    BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXXX XXXX X XXXXXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXX
            XXXXX
            BB BBB BBBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXX XXX XXXXXXXXXXXXX
            XXXXXXXXX
            BBBBB
        XXXXXX
        
        BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFBBBBXX XXXXXXXXXXXBBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX FFFFFFF FF FFXXXXXXX
                            BB BBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX FFFFFFF FF FFXXXXXXX
                            BBBBB
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFFFFFXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXX XX XXX XXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
            XXXXXXXXX
            BBBBB
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX
BBBBBBBB
