BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XXXXXXXXX XXXXXX
        XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXBBBBXXXXXX XXXX XXXXX XXXXX XXX XXXXXXXXX XXXXXXXXXBBBBB
        XXXX
    XXXXXX
    
    BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXX XXXXX X XXXXXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXX
            XXXXX
            BB BBB BBBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXX XXXXXXXXXXX
            XXXXXXXXX
            BBBBB
        XXXXXX
        
        BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX FFFFFFF FF FFXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXX
                            BBBBB
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX  XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                                
                            XXXXXXX
                            XXXXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXX
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXX XX XXX XXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXXX
            XXXXXXXXX
            BBBBB
        XXXXXX
        BBBBB
    XXXXXX
    
    XXXX XXXXXXXXX XXXXXXXXX X XXXXXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXX
        XXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXX XX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXX
    XXX
X
XXXXXXXXX
BBBBBBBB
