BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XX XXXXXXXXXXXXX
            XXXX
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXX XXXXXXXX
                XXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXX XX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXX XXXXX XXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX
                    XXXXXXXX
                    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBXXXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXX XXX X XXXXXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX 
                           XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX
                           XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX
                        XXX XXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX 
                           XXXXXXXX XXXXXXXXXX XXXXXXXX
                           XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX X XXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBXXXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXX XXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                          XXXXXXXXXXXXXXXX XXX X XXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXX

            XXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XX XXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                          XXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                           BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBB
                           XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXX XXXXXXXXXXX XX XX XXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXXXX

                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                           BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBB
                           XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX 
                       XXXXXXX XXXXXXXX XXXXXXXX
                       XXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX 
               XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXX
            XXXXXXX XXXXXXXXXXXXX 
                    XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXX XXXXXXXXX XXXX XXXXXXX XXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXX XXXX XXXXXXXXX XXXX XXXXXXXX XXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXX XXXXXX XX XX XXXXXXXXXX XXXXXX XXXXXX XXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXX XXX XXXX XXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXX XXXXXXXX XXXXXX XXX XXX XXXXXXXX XXXX XXXX X XXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

