BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX
            XXXXXX
            XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXX
        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB






