XXXXXXXXX XXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXX X XXXXXXXBBBBBBBBXXXXXXXX
    XXXXXXXX
        XX XXX XXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX
        XXXXXXXXXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXXXXX XXX XXXXXXX X XXXXXXX X XXXXXXX XXX XXXXXX X XXXXXX X 
                XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXX
    XXXXXXXXX
    XXXXXXXX
        XX XXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX XXX
        XXXXXXXXXXXXXXX X X
            XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X
                XXXXXXX X
                    XXXXXXXXXXX X
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    XX
                    XXXXXXX X
                        XXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        XXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXX XXX XXXXXX XXXXXX XXX XXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXX X
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXXX X XXX X XXXXXXXXX XXXX XXXX XXXX XXXXXX
        X
        
        XX XXXX XXXXX XXXXXX XXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXX XXX X
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X
        
        XX XXXX XXXXXX X XXXXXX XXXX XXXXXX XXXXX XX
        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXX XXX X XXX XXXXXXX XX XX XXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXXX XXXX X XXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXXXXX X XXXX XXXXX XXX XXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XX XXXX XXXXX X XXXXXX XXXXX XXX XXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXX XXXXXX XXXX XXXXXXXXXXX X XXX XXXXX XXXX XXXXXXX XX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXX XXXX XXXXXXX XXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XX XXXXX XXXXXX X XXXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXX XXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXX XXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXX XXXXX X XXXXXXX XXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXX X XXXXX XXXXX XXXX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXX X XXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXXX XXXXXX XXXX XXX XXXXX XXX XXXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXXX XXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXX XXXX XX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX X XXXX XXXXXXX XX
        X
        
        XX XXX XXX XXXXXX XXX XXXX XX XXXXX XXXX X XXXXXX XXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXX XX XXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXX XX XXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXXXX XXXXXXXXXXX XX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXX XXXX XX XXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXXX XX XXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXX XXXXX XXXXXX XXX XXXXXXXX XXX XXXXXXXXXXX XXXX XX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX XX XXX XXXXXXXXXXX XX XXXXXXXXX X XXXXXX XXX XXXX XXXXXXXX XX
        X
        
        XX XXXXXX XXXX XXXXXXXXX XXX XXXXXX XXXXXXXX XX XXXXX XXXX X XXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX X
            XXXXXX XXXXXX XX XXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXX XXXXXXXX XXXXXXXX XXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX XX XXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXXX XXXX XX
        X
        
        XXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXX XXXX XX
        X
        
        XX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXXXXXXX XXX XXXX XXXX XXXXXXX XXXXXXXX XXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXX XXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXX XXX XXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXX XXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX
        X
        
        XX XXXXXXXX XXX XXXX XXXXX XXXXX XX XXXX XXXXXXX XX XXXXXXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXX XXXX XXXX XXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXX XXXXXXXX XXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXXX XXXX XX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X

        XX XXXXXXXXXXX XXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXX X
        
        XX XXXXXXXXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        
        XX XXXXXXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        
        XX XXXXXXX XXXXXXXXXX XXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXXX XXX XXX XXXXXX
                        X XXXX XXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXXX XXX XXX XXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXX XXXX XXXX XXXXXXXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XX XXXXXXX XXXXXX XXXXXX XX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXX XXX XXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXXX X XXXX XXXX XXXX XXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXX X XXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXXX
            XXXXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXXXX XXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXX XXX XXXXX
            XXXXXXXXXXX XXX XXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXX XXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXXXX XXX XXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX
        X
        
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XX XXXXXXX XXXX XXXXXX X XXXXX XXXXXX XX XXXXX XXXXX XXXXX XX XXXXX XX
        XXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXXX
            XXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX X XXXXXXX XX XX XXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X X X XXX XXXXXXXX XXXX XXXX XXXXX X XXX XXX X XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X XXX XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXX
        X
        
        XX XXXXX XXXX XXXXXX XX
        XXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        
        XX XXXX XXXX XXXXXX XX
        XXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXX
        X
        
        XX XXXXXXX XXXXXX XX
        XXXXXXXXXXXX X
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XX XXXXXXXXXXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X
        
        XX XXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXX XXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X
        
        XX XXXXXX XXXX XX
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X
        
        XX XXXXX XXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX
        X
        
        XX XXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
        X
        
        XXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        X
        
        XX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX XX

        XX XXXXX XXXXXX XXXX XXXXXX XXXX XXXXXX XXXXX XX XXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXX XX XXXXX XXXX XX
        X

        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXX XXXXX XX XXXX XXXX XX
        X
        
        XX XXXXXXX XXXXXX XXX X XXXXXXXXXXXXXXXXXXXX XXXXX XX
        XX XXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXX XXXXXXX XX XX XXXXX XXXXXXXXXXX
        X
        
        XX XXXX XXXXX XXXXXX XXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXX XXX XXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXX XXXXXXX XX XX XXXX XXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXBBBBBX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXX XXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBB
                BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXX XXX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBBX
                        
                    XXXXXX
                BBBBBB
            BBBBB
            
            BBBBB BBBBBBBBBBBBBBB
        XXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX
