BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    XXXX XXXX XXXXXX XXXX XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXXXXX
        XXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBB BB BBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXX
                    XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
                    XXX XXXXXXXXXXX XXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXXX
                    XXXXX
                XXXXX
                BBBBB
                XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB






