BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXX XXXXXX XXXX XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXX XXXXXX XX XXXX XXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
    
    XXXX XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBB
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXXX
                            BBB BBBBBB BB BBBBBBB
                            XXXXXXX XXXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXX XXXXXX XXXXXXX XXXXXX
                        BBBB
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXX XXXX XXXXXX X XXXXXX XXXXX XX XXX XXXXXX XXXXXXX
                        XXXX
                        BBBBB
                    XXXXXX
                    
                    XXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                    XXXXXX
                    
                    XXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXX XX XXXX XXXXXXXX XXXX XXXXX XX XXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XX XXXX XXXXXX XXXXX XXXXXXXXX XXXXXX XX XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX BB BBB BBBBBBBXXXXXXXXBBBBBX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXX
                XXXXXXXXX
                BB BBB BBBBBBB
                XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXX XXXX XXXXXX XX XXXXX XXX XXXXXX XXXXXX XXXXXXXX XXXXXXXX
                XXXX
                BBBBB
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
    XX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XX XXXXX XXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX
                
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX X XXXXXX
                
                XX XXXXXXXX XXXXXX XXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX X XXXXXX XXX XXXX XXXXXXXXXX
                    XXXXXXXXX X XXXXX
                X
                
                XX XXXXXXXX XXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXXXXXXX
                    XXXXXXXXX X XXXXX
                X
                
                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXX
                    X
                    XXXXXX XXXXXX
                X
                
                XX XXXX XXXXXXX XXXXX
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXX X XXXXX
                    XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                X
                
                XXXXXX XXXXX
            XXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            X
        X
    XXX
XXXXXXXXX
BBBBBBBB
