BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
    XXXX XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXXXXX
        XXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXX
            XXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
    
    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBB BB BBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXX
                        XXX XXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXBBBBBXX
                                
                            XXXXXXX
                        XXXXX
                        XXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            X
                        XXXXX
                        XXX XXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXX
                                XXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXX
                                XXXX
                                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX XXXXX XXXX XXXXXX XXXXXX XX XXXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                    XXXXXXXXX
                                XXXXXXX
                            XXXXXX
                        XXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXX XX XXXXXX XXXXXXX XXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXX
            XXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX
BBBBBBBB
