BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXX XXXXXX XXXX XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
    
    XXXX XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX
                XXXXXX
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XX XXXX XXX XXXX XXXXXXXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
        
        XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
