BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXXXXX XX XXXXXXXX XXXXXXXXXX
        XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
        XXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXX XXXX XX XXXXXXXX XXXX XX XXXXXXXXXX XXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXX XXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXX
        XXXXX
        
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXX XXXXXXXX XXX
            BBB BBBBBBB BB BBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBB BB BBB
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            
                        XXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXFFFFFFFFFF X FFFFFFFFFFXXXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                                
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            BBBBB
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXXX XXXX XXXX XXXXXX XXXXXX XXXX XX XX XXXXX
XXXXX XXXXXXXXXXXXXXXXX X X
    BBB BBBB BB BBBBBBBBBBBBBBBBBB
    X
        XXX X
        XXXXX XXX
        BB BBBBBBBBBBBBBB BB BBBBBBBBBBB
        XXXXXXXXXX X
        XXXXXXXXXX XFFFFFFFFFFXX
        XXXXXXXX XFFFFFFFFFFXX
        XXXXXXXXXX XFFFFFFFFFFFFX XX XXXXX
        XXXXXXXXXXX XFFFFFFFFFFFFX XX XXXXX
        BBBB
        XXXXXXXXXXXXXX XFFFFFFFFFFF FFFFXX
        XXXXXXXXXXXX XFFFFFFFFFFF FFFFXX
        BBBBB
        XXXXXXXXXX FFFFFX
        XXXXXXX XFFFFFFFFFFFF FFFFFFFFFFFFFFFFXX
        XXXXXXXXX XX
    XBB BBB BBBBBBBBBBBBXBBBBB
    BBBBBB
XX

XXXXX XXXXXXXXXXXX X X
    BBB BBBBBBB BB BBBBBBBBBBBBB
    X
        XXX X
        XXXXXX XFFFFFFFFXX
        XXXXXXX XFFFFFFFFXX
        XXXXXXXXXXXXXX XFFFFFFFFFFF FFFFXX
        XXXXXXXXXXXX XFFFFFFFFFFF FFFFXX
        XXXXXXX XXX
        XXXXXXXXXXXXX FFFFFFFFFFFFFF
    XBB BBB BBBBBBBBBBBBXBBBBB
    BBBBBB
XX

XXXXX XXXXXXXX X X
    BBB BBBBBBB BB BBBBBBBB
    X
        XXX X
        XXXXXXXXXX X
        XXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
        XXXXXXX XXX
        XXXXXXXXXXXXX XFFFFFFFFFFF FFFFX
    XBB BBB BBBBBBBBBBBBXBBBBB
    BBBBBB
XX

XX XXXXXX XXXXXXXX XXXXXXXXX
XXX XXXXXXXXXXX X XXX XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXX XXX XX XXXXX

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXX 
                       XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    
    XXXXX XXXXXXXX X XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXX XXXXXXXXXX XXXXX X XX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
    
    XXX XXXX X XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXX XX X
        XXXX XX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
    XXXX XX XXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXX X XX
    XXX XXXXXXXXXXXX X XX
    
    XXX XXXX X X XX X X XX XXXX X
        XXXX XX XXXXXXX
        XXX XXXX X X XX X X XX XXXX X
            XX XX XXX X XX X X XXXXXXXXX X
                XX XXXXXXXX XXXXX XXXX
                XXXXX XXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXX X X X XX
                XXXX XX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX XX XXXX X XXXXXXXXXXXX X
                XX XXXX XXXXX XXXX
                XXXX XX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
            X XXXX X
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXX XX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXX XX XXXXX XXXXXXXXXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
                
                XXXX XX XXXXXXXX
                XXXXXX
            X
        X
        XXXX XX XXXXXXXX
        XX XXXX X XXXXXXXXXXXX XXXXXX
    X
    
    XXXX XX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXX X XXX
    XXXXX XXXXXX XXXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXX XXXXXXXXXX XXXXX X XX XXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXX
    
    XX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XX XXXXXXXXXX XXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXX XX 
                XXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX
            X
        X XXXX XX XXXXXXXXXX XXX XXXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXX XXX XXXXXXXX X
                XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX
            X
        X
    XXX
    
    XX XXXXX XXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXX
                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX
        X
    XXX
    
    XX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXX
                XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX
        X
    XXX
    
    XXXXXX XXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XX XXXXXXXXXX XXXXXXXX
XXXXXXXXXXXXXXXXX
XXXXXXXXX
BBBBBBBB

