BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB BBBBBBBB X BBBBB X  _('Django site admin') BBBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX _('Django administration') XXXXXXXXXX
BB BBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB
BBBBBBBB

BBBBB BBBBBBBBB
BB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBB
         gettext(u'Welcome,') 
        XXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXX
    BBBBBBBB
    BBBBB BBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX gettext(u'Dashboard') XXXX X
        BBBBB
        BB BBBBBBBB
            XX XXXXXXXX gettext(u'View site') XXXX X
        BBBBB
        BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
            BB BBBBBBBB
                XX XXXXXXXX gettext(u'Documentation') XXXX X
            BBBBB
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Change password') XXXX X
        BBBBB
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXX gettext(u'Log out') XXXXXXXXX
        XXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB
XXXXXX
BBBBB
BBBBBBBB

