"""
Django settings for myProject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file in project root
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+x-o=_pm&g3847ajaj+zg!7qc$yh!!_v(*a52j2-of*z3@s72*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'fluentory-production.up.railway.app']

CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000', 'https://fluentory-production.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',  # Must be before 'django.contrib.staticfiles'
    'cloudinary',  # Cloudinary Python SDK
    'myApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Must be after SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myApp.context_processors.currency_context',
                'myApp.context_processors.hide_switch_view_context',
                'myApp.context_processors.social_links_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Get DATABASE_URL from environment variable - REQUIRED for all environments
# Recommended: Use PostgreSQL for local development (same as production)
# Format: postgresql://[user[:password]@][host][:port][/database]
# Example: postgresql://postgres@localhost:5432/fluentory_dev
DATABASE_URL = os.getenv('DATABASE_URL')

if not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL environment variable is required. "
        "Please set it in your .env file or environment variables."
    )

# Parse DATABASE_URL (supports PostgreSQL, SQLite, and other databases)
# Automatically detects database engine from URL scheme:
# - postgresql:// or postgres:// -> PostgreSQL
# - sqlite:// -> SQLite
db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)

# Only apply PostgreSQL-specific options for PostgreSQL databases
if db_config.get('ENGINE') == 'django.db.backends.postgresql':
    db_config['OPTIONS'] = {
        'connect_timeout': 10,
        'options': '-c statement_timeout=30000'  # 30 second query timeout
    }
    # Disable SSL for local connections (common issue on Windows)
    # Check if host is localhost/127.0.0.1 to disable SSL locally
    host = db_config.get('HOST', '').lower()
    if host in ('localhost', '127.0.0.1', ''):
        db_config['OPTIONS']['sslmode'] = 'disable'
    # Enable connection pooling for PostgreSQL
    db_config['CONN_MAX_AGE'] = 600

DATABASES = {
    'default': db_config
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True  # Enable localization (number/date formatting)

USE_TZ = True

# Supported languages (Arabic prioritized)
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'العربية'),  # Arabic
]

# Path to translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads) - Using Cloudinary
MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cloudinary Configuration
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Get Cloudinary credentials from environment
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '').strip()
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '').strip()

# Verify Cloudinary credentials are loaded
if not CLOUDINARY_CLOUD_NAME or not CLOUDINARY_API_KEY or not CLOUDINARY_API_SECRET:
    print("WARNING: Cloudinary credentials not found in environment variables!")
    print(f"CLOUDINARY_CLOUD_NAME: {'SET' if CLOUDINARY_CLOUD_NAME else 'NOT SET'}")
    print(f"CLOUDINARY_API_KEY: {'SET' if CLOUDINARY_API_KEY else 'NOT SET'}")
    print(f"CLOUDINARY_API_SECRET: {'SET' if CLOUDINARY_API_SECRET else 'NOT SET'}")
else:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )
    print(f"Cloudinary configured with cloud_name: {CLOUDINARY_CLOUD_NAME}")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'student_home'
LOGOUT_REDIRECT_URL = 'home'

# Email Configuration
# For production, configure a real email service (SendGrid, Resend, AWS SES, etc.)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')

# Check if Resend is configured (prioritize Resend if API key exists)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '').strip()
if RESEND_API_KEY:
    # Resend SMTP Configuration
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'resend'  # Resend SMTP username is always 'resend'
    EMAIL_HOST_PASSWORD = RESEND_API_KEY
    DEFAULT_FROM_EMAIL = os.getenv('RESEND_FROM', os.getenv('DEFAULT_FROM_EMAIL', 'noreply@fluentory.com')).strip('"').strip("'")
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    print(f"✓ Resend email configured: {EMAIL_HOST} (from: {DEFAULT_FROM_EMAIL})")
else:
    # Fallback to custom SMTP configuration
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@fluentory.com')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    if EMAIL_HOST == 'localhost':
        print("⚠ WARNING: Email configured for localhost - emails may not send. Set RESEND_API_KEY in .env to use Resend.")

# OpenAI API Key
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Infobip Configuration
INFOBIP_API_KEY = os.getenv('INFOBIP_API_KEY', '')
INFOBIP_BASE_URL = os.getenv('INFOBIP_BASE_URL', 'https://api.infobip.com')
INFOBIP_ACCOUNT_ID = os.getenv('INFOBIP_ACCOUNT_ID', '')
# Channels to sync (comma-separated: SMS,WHATSAPP,EMAIL,VIBER, etc.)
INFOBIP_SYNC_CHANNELS = os.getenv('INFOBIP_SYNC_CHANNELS', 'SMS,WHATSAPP').split(',')
# Auto-update lead status if contacted recently (days)
INFOBIP_AUTO_UPDATE_STATUS_DAYS = int(os.getenv('INFOBIP_AUTO_UPDATE_STATUS_DAYS', '7'))

# Social Media Links - Default fallback URLs for development
# These are used ONLY when database values are blank/None
SOCIAL_LINKS_DEFAULT = {
    'linkedin': 'https://www.linkedin.com/company/fluentory',
    'instagram': 'https://www.instagram.com/fluentory',
    'facebook': 'https://www.facebook.com/fluentory',
    'twitter': 'https://twitter.com/fluentory',
    'whatsapp': 'https://wa.me/962775003006',  # Default WhatsApp number
}
