# Generated by Django 5.1.2 on 2025-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_tutor_image',
            field=models.ImageField(blank=True, help_text='Image for AI Tutor section', null=True, upload_to='site/sections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='certificates_image',
            field=models.ImageField(blank=True, help_text='Image for Certificates section', null=True, upload_to='site/sections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_video_thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail for FAQ section', null=True, upload_to='site/sections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='how_it_works_image',
            field=models.ImageField(blank=True, help_text='Image for How It Works section', null=True, upload_to='site/sections/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_image',
            field=models.ImageField(blank=True, help_text='Image for Pricing section', null=True, upload_to='site/sections/'),
        ),
    ]
