# Generated by Django 5.1.2 on 2025-12-30 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_fix_all_missing_teacher_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini (Fast & Efficient)'), ('gpt-4o', 'GPT-4o (More Capable)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Legacy)')], default='gpt-4o-mini', help_text='OpenAI model to use for AI tutor', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level (0.0 = focused, 2.0 = creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.PositiveIntegerField(default=500, help_text='Maximum tokens in AI response')),
                ('personality', models.CharField(choices=[('friendly', 'Friendly & Encouraging'), ('professional', 'Professional & Formal'), ('casual', 'Casual & Conversational'), ('enthusiastic', 'Enthusiastic & Motivational'), ('patient', 'Patient & Supportive'), ('custom', 'Custom (Use Custom Prompt)')], default='friendly', help_text='Default personality style for the AI tutor', max_length=20)),
                ('custom_system_prompt', models.TextField(blank=True, help_text='Custom system prompt (overrides personality if set). Use {course_title}, {lesson_title} as placeholders.')),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for the AI tutor (e.g., teaching style, focus areas)')),
                ('include_lesson_context', models.BooleanField(default=True, help_text='Include lesson content in AI context')),
                ('include_course_context', models.BooleanField(default=True, help_text='Include course description in AI context')),
                ('max_conversation_history', models.PositiveIntegerField(default=10, help_text='Number of previous messages to include in context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_settings', to='myApp.course')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Tutor Settings',
                'verbose_name_plural': 'AI Tutor Settings',
            },
        ),
    ]
