# Generated by Django 5.1.2 on 2025-12-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_aitutorsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('SAR', 'SAR - Saudi Riyal'), ('AED', 'AED - UAE Dirham'), ('JOD', 'JOD - Jordanian Dinar'), ('GBP', 'GBP - British Pound')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='myApp.course')),
            ],
            options={
                'verbose_name': 'Course Pricing',
                'verbose_name_plural': 'Course Pricing',
                'ordering': ['currency'],
                'unique_together': {('course', 'currency')},
            },
        ),
    ]
