# Generated by Django 5.1.2 on 2025-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_add_course_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('live', 'Live'), ('hybrid', 'Hybrid')], default='recorded', help_text='Type of course: Recorded (self-paced), Live (scheduled sessions), or Hybrid (combination)', max_length=20),
        ),
    ]
