# Generated by Django 5.1.2 on 2025-12-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_add_booking_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['day_of_week', 'start_time', 'start_datetime'], 'verbose_name_plural': 'Teacher Availabilities'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='online_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='When online status was last updated', null=True),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking this slot'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Block this time slot from being booked'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='slot_type',
            field=models.CharField(choices=[('recurring', 'Recurring (Weekly)'), ('one_time', 'One-Time Slot')], default='recurring', max_length=20),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
