# Generated by Django 5.1.2

from django.db import migrations, models


def backfill_permission_level(apps, schema_editor):
    """Backfill existing Teacher rows with default permission_level"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Set default for new rows
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'myApp_teacher' 
                    AND column_name = 'permission_level'
                ) THEN
                    -- Set default for new rows
                    ALTER TABLE "myApp_teacher" 
                    ALTER COLUMN permission_level SET DEFAULT 'standard';
                    
                    -- Backfill NULL values
                    UPDATE "myApp_teacher" 
                    SET permission_level = 'standard' 
                    WHERE permission_level IS NULL;
                END IF;
            END $$;
        """)


def reverse_backfill(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_add_online_status_updated_at'),
    ]

    operations = [
        # Update database: set default and backfill NULL values
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'myApp_teacher' 
                        AND column_name = 'permission_level'
                    ) THEN
                        -- Set default for new rows
                        ALTER TABLE "myApp_teacher" 
                        ALTER COLUMN permission_level SET DEFAULT 'standard';
                        
                        -- Backfill NULL values
                        UPDATE "myApp_teacher" 
                        SET permission_level = 'standard' 
                        WHERE permission_level IS NULL;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update model state only (column already exists in DB)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='teacher',
                    name='permission_level',
                    field=models.CharField(
                        choices=[('standard', 'Standard'), ('premium', 'Premium'), ('admin', 'Admin')],
                        default='standard',
                        help_text='Permission level for the teacher',
                        max_length=20
                    ),
                ),
            ],
        ),
    ]
