# Generated by Django 5.1.2 on 2026-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_add_can_manage_schedule_to_courseteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclasssession',
            options={'ordering': ['-scheduled_start'], 'verbose_name': 'Group Session', 'verbose_name_plural': 'Group Sessions'},
        ),
        migrations.AddField(
            model_name='course',
            name='booking_type',
            field=models.CharField(choices=[('none', 'No Booking System'), ('group_session', 'Group Session (Seat-Based)'), ('one_on_one', '1:1 Booking (Availability-Based)')], default='none', help_text='Type of booking system enabled for this course: Group Session (seat-based) or 1:1 (availability-based)', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_booking_approval',
            field=models.BooleanField(default=False, help_text='For 1:1 bookings: Requires teacher approval before confirmation'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='requires_booking_approval',
            field=models.BooleanField(blank=True, help_text='Override course-level approval setting for this teacher. If null, uses course setting.', null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='enable_waitlist',
            field=models.BooleanField(default=False, help_text='Allow waitlist after all seats are taken'),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom / Google Meet / Custom meeting link'),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='total_seats',
            field=models.PositiveIntegerField(default=10, help_text='Total seat capacity for this group session'),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('booking_closed', 'Booking Closed')], default='scheduled', max_length=20),
        ),
    ]
