# Generated by Django 5.1.2 on 2026-01-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_add_dual_booking_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasssession',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Phase 2: Alias for total_seats', null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='end_at_utc',
            field=models.DateTimeField(blank=True, help_text='Session end time in UTC', null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='meeting_passcode',
            field=models.CharField(blank=True, help_text='Meeting passcode/password', max_length=50),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='meeting_provider',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams'), ('custom', 'Custom')], default='zoom', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='seats_taken',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of confirmed bookings (updated via signal)'),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='start_at_utc',
            field=models.DateTimeField(blank=True, help_text='Session start time in UTC', null=True),
        ),
        migrations.AddField(
            model_name='liveclasssession',
            name='timezone_snapshot',
            field=models.CharField(blank=True, help_text='Teacher timezone at creation time (e.g., "America/New_York")', max_length=50),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='scheduled_start',
            field=models.DateTimeField(help_text='Legacy field - use start_at_utc'),
        ),
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one_on_one_series', '1:1 Series'), ('group_series', 'Group Series')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='weekly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Interval for frequency (e.g., every 2 weeks)')),
                ('days_of_week', models.CharField(blank=True, help_text='Comma-separated days (0=Monday, 6=Sunday) for weekly recurrences', max_length=50)),
                ('occurrence_count', models.PositiveIntegerField(blank=True, help_text='Total number of occurrences', null=True)),
                ('until_date', models.DateTimeField(blank=True, help_text='Series end date', null=True)),
                ('default_meeting_link', models.URLField(blank=True)),
                ('default_meeting_id', models.CharField(blank=True, max_length=100)),
                ('default_meeting_passcode', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_series', to='myApp.course')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_series', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_series', to='myApp.teacher')),
            ],
            options={
                'verbose_name': 'Booking Series',
                'verbose_name_plural': 'Booking Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('group_session', 'Group Session'), ('one_on_one', '1:1 Booking')], max_length=20)),
                ('start_at_utc', models.DateTimeField(help_text='Session start time in UTC')),
                ('end_at_utc', models.DateTimeField(help_text='Session end time in UTC')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('student_note', models.TextField(blank=True, help_text='Student notes or questions')),
                ('teacher_note', models.TextField(blank=True, help_text='Teacher notes (internal)')),
                ('seats_reserved', models.PositiveIntegerField(default=1, help_text='Number of seats reserved (default 1)')),
                ('decision_at', models.DateTimeField(blank=True, help_text='When approval decision was made', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('student', 'Cancelled by student'), ('teacher', 'Cancelled by teacher'), ('admin', 'Cancelled by admin'), ('system', 'Cancelled by system'), ('conflict', 'Scheduling conflict'), ('emergency', 'Emergency')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Who cancelled the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_cancellations', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_bookings', to='myApp.course')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Teacher or admin who decided', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_decisions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='FK to LiveClassSession (nullable for 1:1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_class_bookings', to='myApp.liveclasssession')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_bookings', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_bookings', to='myApp.teacher')),
            ],
            options={
                'verbose_name': 'Live Class Booking',
                'verbose_name_plural': 'Live Class Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_index', models.PositiveIntegerField(help_text='Occurrence number in series (1, 2, 3, ...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myApp.bookingseries')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_items', to='myApp.liveclassbooking')),
            ],
            options={
                'verbose_name': 'Booking Series Item',
                'verbose_name_plural': 'Booking Series Items',
                'ordering': ['occurrence_index'],
            },
        ),
        migrations.CreateModel(
            name='SessionWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='myApp.liveclasssession')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Waitlist',
                'verbose_name_plural': 'Session Waitlists',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherBookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_approval_for_one_on_one', models.BooleanField(default=False, help_text='Require approval for 1:1 bookings')),
                ('requires_approval_for_group', models.BooleanField(default=False, help_text='Require approval for group session bookings (usually false)')),
                ('min_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours notice before booking allowed')),
                ('cancel_window_hours', models.PositiveIntegerField(default=24, help_text='Hours before start when cancellation is allowed')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time before session (minutes)')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time after session (minutes)')),
                ('max_bookings_per_day', models.PositiveIntegerField(blank=True, help_text='Optional limit on bookings per day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='If null, applies as default policy for teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='myApp.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='myApp.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Booking Policy',
                'verbose_name_plural': 'Teacher Booking Policies',
            },
        ),
        migrations.AddIndex(
            model_name='liveclassbooking',
            index=models.Index(fields=['booking_type', 'status'], name='myApp_livec_booking_d999a9_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassbooking',
            index=models.Index(fields=['student_user', 'start_at_utc'], name='myApp_livec_student_58042b_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassbooking',
            index=models.Index(fields=['teacher', 'start_at_utc'], name='myApp_livec_teacher_dc2ac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseriesitem',
            unique_together={('series', 'occurrence_index')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionwaitlist',
            unique_together={('session', 'student_user')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherbookingpolicy',
            unique_together={('teacher', 'course')},
        ),
    ]
