# Generated by Django 5.1.2 on 2026-01-06 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_populate_phase2_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='liveclassbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'group_session')), fields=('student_user', 'session', 'start_at_utc'), name='unique_group_booking'),
        ),
        migrations.AddConstraint(
            model_name='liveclassbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_type', 'one_on_one')), fields=('student_user', 'teacher', 'start_at_utc'), name='unique_one_on_one_booking'),
        ),
    ]
