# Generated by Django 5.1.2 on 2026-01-06 19:28
# Updated to use SeparateDatabaseAndState since scheduled_end column already exists in database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_add_reminder_sent_field'),
    ]

    operations = [
        # Use SeparateDatabaseAndState because scheduled_end column already exists in database
        # We only need to update Django's state to reflect that it's now nullable
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='liveclasssession',
                    name='scheduled_end',
                    field=models.DateTimeField(blank=True, help_text='Legacy field - computed as scheduled_start + duration_minutes', null=True),
                ),
            ],
            database_operations=[
                # No database operations - column already exists, just make it nullable
                migrations.RunSQL(
                    sql='ALTER TABLE "myApp_liveclasssession" ALTER COLUMN "scheduled_end" DROP NOT NULL;',
                    reverse_sql='ALTER TABLE "myApp_liveclasssession" ALTER COLUMN "scheduled_end" SET NOT NULL;',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='Zoom / Google Meet / Custom meeting link'),
        ),
    ]
