# Generated by Django 5.1.2 on 2026-01-06 19:52
# Updated: meeting_url column exists in database, need to map meeting_link field to it

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_liveclasssession_scheduled_end_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState because meeting_url column already exists in database
        # We only need to update Django's state to reflect the db_column mapping
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='liveclasssession',
                    name='meeting_link',
                    field=models.URLField(blank=True, db_column='meeting_url', default='', help_text='Zoom / Google Meet / Custom meeting link'),
                ),
            ],
            database_operations=[
                # No database operations - column already exists with correct structure
            ],
        ),
    ]
