# Generated by Django 5.1.2 on 2026-01-06 20:09
# Updated: Columns already exist, only update Django's state

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_fix_meeting_columns'),
    ]

    operations = [
        # Use SeparateDatabaseAndState because columns already exist in database
        # We only need to update Django's state to reflect the field changes
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='liveclasssession',
                    name='meeting_link',
                    field=models.URLField(blank=True, default='', help_text='Zoom / Google Meet / Custom meeting link'),
                ),
                migrations.AlterField(
                    model_name='liveclasssession',
                    name='seats_taken',
                    field=models.PositiveIntegerField(default=0, help_text='Cached count of confirmed bookings (updated via signal)'),
                ),
            ],
            database_operations=[
                # No database operations - columns already exist with correct structure
            ],
        ),
    ]
