# Generated by Django 5.1.2 on 2026-01-07 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_fix_enrollment_teacher_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_reset',
            field=models.BooleanField(default=False, help_text='Require user to change password on next login'),
        ),
        migrations.CreateModel(
            name='SecurityActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('force_password_reset', 'Force Password Reset'), ('account_suspended', 'Account Suspended'), ('account_activated', 'Account Activated'), ('role_changed', 'Role Changed'), ('permission_changed', 'Permission Changed')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.TextField(blank=True, help_text='Additional action metadata (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Action Log',
                'verbose_name_plural': 'Security Action Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_secur_created_ff0b55_idx'), models.Index(fields=['target_user', '-created_at'], name='myApp_secur_target__aa1999_idx'), models.Index(fields=['admin_user', '-created_at'], name='myApp_secur_admin_u_8df972_idx')],
            },
        ),
    ]
