# Generated by Django 5.1.2 on 2026-01-08 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_userprofile_force_password_reset_securityactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(help_text='Email address of the gift recipient', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Optional recipient name', max_length=255)),
                ('sender_name', models.CharField(blank=True, help_text='Optional sender name', max_length=255)),
                ('gift_message', models.TextField(blank=True, help_text='Optional gift message')),
                ('status', models.CharField(choices=[('pending_claim', 'Pending Claim'), ('claimed', 'Claimed')], default='pending_claim', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for gift claim', null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_purchased', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_enrollments', to='myApp.course')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_enrollment', to='myApp.enrollment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_enrollments', to='myApp.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gift_token'], name='myApp_gifte_gift_to_4a3813_idx'), models.Index(fields=['recipient_email', 'status'], name='myApp_gifte_recipie_2b8085_idx'), models.Index(fields=['status', 'created_at'], name='myApp_gifte_status_bf7534_idx')],
            },
        ),
    ]
