# Generated by Django 5.1.2 on 2026-01-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_giftenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclasssession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('booking_closed', 'Booking Closed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveclasssession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='myApp.teacher'),
        ),
        migrations.CreateModel(
            name='LiveClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for assignment/reassignment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('new_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history_new', to='myApp.teacher')),
                ('old_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history_old', to='myApp.teacher')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='myApp.liveclasssession')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
