# Generated by Django 5.1.2 on 2026-01-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_alter_liveclasssession_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('referral', 'Referral'), ('event', 'Event'), ('website', 'Website'), ('gift', 'Gift'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('negotiating', 'Negotiating'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Linked user account if exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Assigned staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftEnrollmentLeadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gift_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='myApp.giftenrollment')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_enrollments', to='myApp.lead')),
            ],
            options={
                'verbose_name': 'Gift Enrollment Lead Link',
                'verbose_name_plural': 'Gift Enrollment Lead Links',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentLeadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='myApp.enrollment')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myApp.lead')),
            ],
            options={
                'verbose_name': 'Enrollment Lead Link',
                'verbose_name_plural': 'Enrollment Lead Links',
            },
        ),
        migrations.CreateModel(
            name='LeadTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Status Changed'), ('LEAD_OWNER_CHANGED', 'Owner Changed'), ('LEAD_NOTE_ADDED', 'Note Added'), ('LEAD_NOTE_EDITED', 'Note Edited'), ('GIFT_CREATED', 'Gift Created'), ('GIFT_LINKED_TO_LEAD', 'Gift Linked to Lead'), ('GIFT_UNLINKED_FROM_LEAD', 'Gift Unlinked from Lead'), ('GIFT_CLAIMED', 'Gift Claimed'), ('USER_LINKED_TO_LEAD', 'User Linked to Lead'), ('USER_UNLINKED_FROM_LEAD', 'User Unlinked from Lead'), ('ENROLLMENT_CREATED', 'Enrollment Created'), ('ENROLLMENT_LINKED_TO_LEAD', 'Enrollment Linked to Lead'), ('ENROLLMENT_UNLINKED_FROM_LEAD', 'Enrollment Unlinked from Lead'), ('LEAD_CONVERTED_TO_ENROLLED', 'Lead Converted to Enrolled'), ('AUTO_LEAD_CREATED_FROM_GIFT', 'Auto Lead Created from Gift'), ('AUTO_LINK_PERFORMED', 'Auto Link Performed'), ('MANUAL_OVERRIDE_PERFORMED', 'Manual Override Performed')], max_length=50)),
                ('summary', models.TextField(help_text='Human-readable event summary')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed action, null for system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='myApp.lead')),
            ],
            options={
                'verbose_name': 'Lead Timeline Event',
                'verbose_name_plural': 'Lead Timeline Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='myApp_lead_email_e18cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='myApp_lead_status_a865aa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='myApp_lead_source_7ebbd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='giftenrollmentleadlink',
            unique_together={('gift_enrollment', 'lead')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentleadlink',
            unique_together={('enrollment', 'lead')},
        ),
        migrations.AddIndex(
            model_name='leadtimelineevent',
            index=models.Index(fields=['lead', '-created_at'], name='myApp_leadt_lead_id_b8f59a_idx'),
        ),
    ]
