# Generated by Django 5.1.2 on 2026-01-08 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_lead_giftenrollmentleadlink_enrollmentleadlink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('gift', 'Gift Enrollment'), ('live_class', 'Live Class'), ('lead', 'Lead'), ('enrollment', 'Enrollment'), ('teacher', 'Teacher')], max_length=20)),
                ('entity_id', models.PositiveIntegerField(help_text='ID of the related entity')),
                ('event_type', models.CharField(choices=[('gift_claimed', 'Gift Claimed'), ('teacher_assigned', 'Teacher Assigned'), ('teacher_unassigned', 'Teacher Unassigned'), ('teacher_reassigned', 'Teacher Reassigned'), ('lead_status_updated', 'Lead Status Updated')], max_length=50)),
                ('summary', models.TextField(help_text='Human-readable summary of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_activ_created_cd9c3d_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='myApp_activ_entity__c6f2f0_idx'), models.Index(fields=['event_type', '-created_at'], name='myApp_activ_event_t_a5a4f2_idx'), models.Index(fields=['actor', '-created_at'], name='myApp_activ_actor_i_0b11b8_idx')],
            },
        ),
    ]
