# Generated by Django 5.1.2 on 2026-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='infobip_channel',
            field=models.CharField(blank=True, help_text='Last channel used (SMS, WhatsApp, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='infobip_last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time synced from Infobip', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='infobip_profile_id',
            field=models.CharField(blank=True, help_text='Infobip People profile ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leadtimelineevent',
            name='event_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Status Changed'), ('LEAD_OWNER_CHANGED', 'Owner Changed'), ('LEAD_NOTE_ADDED', 'Note Added'), ('LEAD_NOTE_EDITED', 'Note Edited'), ('GIFT_CREATED', 'Gift Created'), ('GIFT_LINKED_TO_LEAD', 'Gift Linked to Lead'), ('GIFT_UNLINKED_FROM_LEAD', 'Gift Unlinked from Lead'), ('GIFT_CLAIMED', 'Gift Claimed'), ('USER_LINKED_TO_LEAD', 'User Linked to Lead'), ('USER_UNLINKED_FROM_LEAD', 'User Unlinked from Lead'), ('ENROLLMENT_CREATED', 'Enrollment Created'), ('ENROLLMENT_LINKED_TO_LEAD', 'Enrollment Linked to Lead'), ('ENROLLMENT_UNLINKED_FROM_LEAD', 'Enrollment Unlinked from Lead'), ('LEAD_CONVERTED_TO_ENROLLED', 'Lead Converted to Enrolled'), ('AUTO_LEAD_CREATED_FROM_GIFT', 'Auto Lead Created from Gift'), ('AUTO_LINK_PERFORMED', 'Auto Link Performed'), ('MANUAL_OVERRIDE_PERFORMED', 'Manual Override Performed'), ('INFOBIP_SYNC_UPDATED', 'Updated from Infobip Sync'), ('INFOBIP_SYNC_CREATED', 'Created from Infobip Sync')], max_length=50),
        ),
    ]
