# Generated by Django 5.1.2 on 2026-01-23 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_add_lesson_content_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number in international format (e.g., +1234567890)', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook page/profile URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram profile URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Full LinkedIn profile/page URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Full Twitter/X profile URL'),
        ),
    ]
