BBBB BBBBBB BBBB
XXXXXXXXX XXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
XXXXX XXXXXXFFFFFFFFFFFFX XXXXXBB BBBBBBBBBBBBBBBB BB BBBBXXXBBBBXXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXX X XXX XXXXXX XXX XX XXXXX XXXXXXXXBBBBBBBBXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X
                XXXXXXX X
                    XXXXXXXXXXX X
                        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
    XXXXXXX
        XX XXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXX XXXX XXX XXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXXXX XXXX XXXXXXXXXX XXX XXXXXX XXXXXX XXXXX XX
        XX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XX XX XXXXXXX XXX XXXXXX XX
        XX XXXXXXXX XXXXX XXXXXXXXXX XXX XXXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXX XXXX XXXXXXXX X XXXXXXXXXX XX XX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXX XXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXXXX XXX XXXXXXXXX XXXX XXX XXXXX XXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXX XXXX XXXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
        X
        
        XX XXXXXX XXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXX X XXXXXXXX XXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXXXX XXX XXXXXXXX XXXXXXX XX XXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXX XXXXXXXXXX X XXXXXX XX XXXXXXX XXXX XXXXXXXXXX XX
        XX XXXXXX XX X XXXXXX XXXXX XX XXXX XX XXXXXXXXX XX
        XX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXX XX XXXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXXXX XXX XXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXX XXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    
    XXXXX XXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
    XXXXXXX
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    
    XXXX XXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXX XXXXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            
            XXXX XXXX XXXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXXX XXX XXX X XXXX XXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XXXX XXX
            XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXX XX XXXXX XXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX
        XXXX XXXX XX XXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        
        XXXX XXXXXXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXX XX XXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXX XXXXXXXXX XXXX XXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    
    XXXXXXXX
        XX XXXXXX XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX

        XX XXX XXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXX X X
            X
                XXXXXXXXX XXXX XXXX XXX XXXXXXXXX XXXX XXXXXXX
                XXXXXXXXXXXX XXXX XXXX XXXXXX XX XXXX XXXXXXX XX XXXXXXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXX XX XXX XXXXX XXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXX XX XXXXXXXX
                XXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX
            XX
            X
                XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXX XXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XX XXXX XXXXXXXXXXXX XXXX XXX XX XXXXXXXXX XXXXXXXX XX XXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXXX XXXXXX XXX XXX XX XXXXXX XXXXXXXXXXXX
                XXXXX XXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX
            X
                XXXXXXXXX XXXX X XXXXX XX XX XXX XXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXX XX XXXXX XXX XXXXXX XXX XX XXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
            XX
            X
                XXXXXXXXX XXX XXXX XXXXXXXX XXX XXXXXXXXXXXX
                XXXXXXXXXXXX XXXXX XXXXXXXXX XX XXXXXXXX XXX XXXXXXXX XX XXX XXXXXXX XXX XXXXXXXXX XXXX XXXXXXX XXX XXXXX XX XXX XXXXX XXXXXX XXX XXX XXXXXXX XXXXX XXXX XXXXXXXX XX XXXXXXXXXXX
                XXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
            XX
            X
                XXXXXXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XX XXXXXXXXX XXX XXXX XXXXXXXX XX XXXXX XXX XXXXXXXXXX XXXXX XXX XXXX XXXXXXXXXXX XXX XXXXXXX XXX XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX
            X
        XX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            
            XX XXX XXXXX XXXX XX XXXXXX XX XXXXXXX
            XX XXXXXX XXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXX XXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXX
                
                XX XX XXXXXXXX XXX XXXXXX XXXXX XXXXX XXX XXXXXXXXXX XXXX XXX XXXXXXX XXXX
                XX XXXXXXXXXXX X
                    XX XXXX XXXXXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    
                    XX XXXXXX XXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        XXX
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXX X XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XX 
                    XXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
            X
        X

        XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX

        XX XXXXXX XXXXXX XXX XXXXXX XXXXX X XXXXXXX XXXX XXXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXX XXXXXXX
                
                XX XXXXXXX XXXX XXXX XXX XXXXXXXX XXXX XXXXXXX XXX XXXXXXXX XXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXXXXXX XX XX XXXX XXXXX
                
                XXXXX XXXXXXXX X XXXXXXXXXXXXX
                XX XXXXXXXXXXX XXXXXXX XX XXXXX XXXX
                
                XX XXXXX XX XXXXX XX XXX XXXXXXX XXXX XXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXX
                
                XX XXXXX XX XXXX XXXXXX XX XXXXXXXX XXXXXXX XXXX X XXX XXX XX XX XXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXX XXX XXX X XXXXXXXXX
                
                XX XX XXXX XXXXXX XX XXXXXXXX XXXXXX XXX XXXXX XXX XX XXXXXXXXX XXXXX XXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX X
                    XX XXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXX XXXXX XXXX XXXX
                    XXXXXXX XX XXXXX XXXXXXX XXXXXXXX XXX XXXXXXX XXXXXXXX
                X
                
                XX XX XXXXX XX XXX XXXX XXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXXX
                XX XXXXXXXXXXXXXX X
                    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
                        XX XXX XXXXX XXXXXX XXX XXXXXX XXXXXXX XXXXXXX X XXXX XXXXXXXXX XXXXX
                        XXXXX XXXXXX X XXXXXXXXXXXX X XXX
                        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXX
                        
                        XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXX
                        XXX
                    X
                X
            XXX
        XXX
        
        XX XXXXXX XXXXXX XXXXXX XXX XXXXXX XXXXX XXXXX XXXXXXXXXX XX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX X
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX X
                    XX XXXXX XXXXX XX XXXXXX XXXX XX XXXXX XXXXXXXX
                    XXXXXXXXXXXXX XX X
                        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
                        XXXXX XXXXXX X XXXXXXXXXXXX X XXX
                        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXX
                        
                        XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXX
                        XXX
                    XX XXXXX
                X
            X
        XXX

        XX XXXX XX XXX XXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXX XXXXXX XXXXX XX XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XX XXXXXXXXXXXXXXX X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
        
        XX XXXXXX XXXXXX XX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXX
                XXXX XX
                XXXXXXXXX XXXXXXXX
            XXX
        XXX

        XX XXXXXXX XXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXX XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        X
        
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
                XX XXXXXXXXX XXX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        X
        
        XX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX X XXXXXX X
            XX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXX X X
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX X XXXXXXXXX X XXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXX X
            XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXX X XXX
                
                XX XXXXXXXX XX XXXXXXXX XXXXXXXX XXXX XXXXXX XXX XXXX XXXXXX
                XXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXX XXXX XX XXXXX XXX XXXX XX XXXXX XXXXXXXXX XXXXXX XXXX XX XX XXXX XXXXXXXXXXX
                XX XXXXX
            X
        X
        
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        X
        
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
                XX XXXXXX XXX XXXXXXXX X
                    XXXXXXXXXXXXXX
                X
            XXX
        X
        
        XX XXXXXXX XXXX XXXXXX XX XXXXXX XXXXX XXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXX XX XXXXXXX
            
            XX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                XX XXX XXXXXXXXXX XXXXXXX XX XXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                
                XX XXXXX XXXXXXX XXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXX
                XX XXXXXX XXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                X XXXX X
                    XX XXXXX XXXXXXXX XXXXX XXXXX XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                X
            XXX
            
            XX XXXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXX X X
                XXXXX XXXXX
                XXXXXXXXXXX XXXX XXX XXXX XXXXX XX XXXXXXX XXXX XXXXXXX XX XXX XXXX XXXXXX
                XXXXXXXXXX XXX
            XX
            
            XXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
            
            XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXX X XXXXX
                
                XXXXXXXXXXXXXXXXXXXXX XX X
                    XX XXXXXXXXXXXXXXXXXXXXXX X
                        XX XXXXXXX XX XXXXXXXX XX XX XXXXXXXX X XXXX XX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    X XXXX X
                        XX XXXXXXX XX XXXXXXX XXXXXXXX X XXXX XXX
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXX XXX XXXX XXXXXXXXX XX XXX XXXXXXX XX XXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXX XXXX XX XXXXXXXXXXX X XX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        X
                        XX XXXX XXX XXXX XXXXXXXXX XXXX XXX XXXXXXX XX XXXXX XXXXXXXX
                        XXXX XX XXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXX X XXXXXXXXXXXXXXXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        X
                    X
                XXX
                
                XXXXXXXXXXX X XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX
            
            XX XXXXXXX XXX XXXXXXXX XXXXXX XXX XXXXX XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                XX XXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
            
            XX XXXXX XXXXXX XXXXXXXXX XXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXX
            XX X XXXXXXXX XXXX XXX
            
            XX XXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XX XXXX
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                    XX XXXXXX X XX X
                        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                        XX XX XXXXXXX XX XXXXXXX XXXXXXX XX XXXXX XXXX XX XX
                        XX XXXXXXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXX X XX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        X
                    X
                XXX
            XX XXXXX
        X
        
        XX XXXXXXXXXX XXXX XXX XX XXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X XXXX X
            XX XXX XXXXXXX XXXXXXX XXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXX XXXX XXXXXXXXXXX XXX XXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXX XXXX XXXXXXX XX XXXXXXX XX XXXX XXXX XXXXXXXXX
            XXXXXXXXXXXXX XX X
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                X
            XX XXXX
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
