XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXX
            XXXXXXXX XXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXXX XX
            XXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXX XXX XX
            XXXXXXXXXXX X X XXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX
        X
        
        XXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            X
        X
        
        XXXXXXXXXXXXXXXXX X X
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
        X
    XXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
    XXXXXX
XXXXXXXX
