XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXXX X XXXXXXXBBBBBBBBXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXX X
                XXXXXXX X
                    XXXXXXX X
                        XXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXX XXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XXXXXXXXXX XXXXXXX X
            XX X
                XXXXXXXXXX XXXXXXXXXXXXXXXXXX
            X
            XXXX X
                XXXXXXXXXX XXXXXXXXXXXXXXXXX
            X
        X
        
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX XX XXXXXXXXX
        X
        
        XX XXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXX X
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXXX X XXX X XXXXXXXXX XXXX XXXX XXXX XXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXX XXX X XXX XXXXXXX XX XX XXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXX X XXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXX XX
        XX XXXX XXXXXXXXXXX XXXXXX XXX XXXXXXX XXXXX XXXX XXXXX XXXX XXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX X
            XX XXXXX XX XXXXXXX XXX XXXX XXXXXXXXXX XX XXXXXXX XX XXXXXXXX XXXXX XX
        X
        
        XX XXXXXX XXXXXXXXX XXXXXX XXXXX XXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XXX XXX XXXXXX X XXX XXXX XXXXXXX XXX XXX XXXXXX XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XXX XXX XXXXXX X XXXX XXXX XXXXXXX XXX XXX XXXXXX XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XX XXXX XXXXXX XXX XXXXXXX XXXXXXX XXXXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXX XX XXXX XXXXX X XXXX XXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXX XXXXXXX XXXXXXXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXX X XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX X XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXXXXXX XX XXXXX X XXXXXX XX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXXXXX X XXXXXXX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXXXXXXX X XXXXXX XXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXXX X XXXXXXXX XXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXXX XXXX XX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX X XXX XXX XXXXXXX XX XX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXX XXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX X XXXXX XXXXX XXXX XXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXXX XXXXXX X XXX XXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXXX XXXXXX X XXX XXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXX XXXXX XXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXX X XXXX XXXXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXX XXXXXXXXXXX XX XXX XXXX XXXXX XXXXX XXXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXX XXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XX XXXXX XX XX XXX XXXX XXXXXXXXXX XXXXX XXX XXXXXXXX XX
        X
        
        XX XXXXX XXXXX XXXX XXXXXXX XXXX XXXXXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XXX XXX XXXXXX X XXX XXXX XXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXX XXXXXXX X XXXXXX XXX XXXX XX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XXXXX XXXXXX X XXXXXX XXXXX XXXX XX XXXX XXXXX XXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXX XXXX XX XXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXX XX XXXX XXXXX XXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXX XXXXXXXX XXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        
        XX XXXXX XXXXX XXXXXXX XXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXX XXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXXXBBBBBX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        
        XXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBB
        XXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX

