BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

            XXXX XXXXXX XX XXXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                XXXXXXX 
                    XXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXX
                X
                    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBB BB BB BBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX
                
                BBBBBBB BBBBBBBBBBBBBBB BB BBBBBBB BB BBBBBBBBBBBBBBBB
                BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        BBB BBBB BB BBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBB
                                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                                        FFFFFFFFF FF X FFFFFFFFF FF
                                    XXXXXX
                                    BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
                                        BB BBBBBBBBBBBBBBBXXXX FFFFFFF FFBBBBB
                                        BB BBBBBBBBBBBBBBBBXXXXX FFFFFFF FFBBBBB
                                    XXXXXX
                                    BBBBB
                                BBBB
                                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFF FF FFXXXXXXX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                                        FFFFFFFFF FF X FFFFFFFFF FF
                                    XXXXXX
                                BBBBB
                            XXXXXX
                            
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                                BBBBBBBBBB
                                XXXXXXX 
                                    XXXXXXXXXXXXX 
                                    XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                                X
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
                                XXXXXXXXX
                            XXXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXX XXXX XXXXX XX XXX XXXXXXX XXXXXX XXXXX XXXX XXXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB




