BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXX XXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXX
            XXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                        XXXX XXXXX XXXXXXX XXXXXXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXBBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXBBBBBXX
                                
                            XXXXXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXFFFFFFFFF FF X FFFFFFFFF FFXXXXXXX
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBB
                                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXX
                                BBBBB
                            BBBBB
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXX X  XXXXX XXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    BBBB
                        XXXX XXX XXXXXXX XXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFF FFFFFFFFXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXBBBB BBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXBBBBBXX
                                
                            XXXXXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                            XXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXXFFFFFFFFF FFXXXXXXX
                            XXXXXX
                            BBBBB
                            BB BBBBBBBBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB BB BBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBB
                                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXX
                                BBBBB
                            BBBBB
                        XXXXXX
                    BBBBB
                    
                    XXXX XXXXXXXXXXX XXXXX XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                            BB BBBBBBBBBBBBBB BB BBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXXXXX
                            XXXXXXX
                            BBBBB
                        BBBB
                            BB BBBBBBBBBBBBBB BB BBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXXXXX
                            XXXXXXX
                            BBBBB
                        BBBBB
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        BBBBB

        XXXX XXXX XXXXXXXX XXX
        BB BBBBBBBBBBBBB
        XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXX
            XXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                                
                            XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXX
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFF FFFFFFFFXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                                
                            XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXX
                            BBBBB
                        XXXXXX
                    BBBBB
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        BBBBB

        BB BBB BBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX XXX XXXXXXXX XXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
            XXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX
BBBBBBBB




