BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            
            XXXX XXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXFFFFFFF FF FFXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXFFFFFFFFF FF X FFFFFFFFF FFXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX X  XXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXX XXXX XXXXXX XXXXXX XXXXXXXXXX X XXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXX XXX
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XX XXXX XXX XXXXXXXX XX XXX XXXXXXXXXXXX
                XXXXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBB BB B BBB BBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX XX XXXXX XXX XXX XXX XXXX XXX XXXXXXXXXXXXX
                XXXXXX
            BBBBB

            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXXXXX 
                        XXXXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXXXXX 
                        XXXXXXXX 
                        XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXX
                    XXXXXXXXXXXX
                XXXXXX

                XXXXXXX 
                    XXXXXXXXXXXXX 
                    XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
                X
                    BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                    BBBB
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX
                    BBBBB
                XXXXXXXXX
            XXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB




