BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX X XXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXX XXXXXX XXXXXXX
        XXXXXX
        
        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
        
        XXXX XXXXX XXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
            
            BB BBB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXX XX XXXXXXX XX XXX XX XXXX XXXX XXXXX XXXXXXX XX XXXXX XXXX XXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXX
                    XX XXXXXXBBB BBBBBBBBXXXXXXXFFFFFFFFFXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBX 
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBX 
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XX
                    XXXX
                XXXXXX
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXX XXX XXXXXXX XXXXXX XXXXX XXXXX XX XXXXX XXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXX XXXX
                XXXXXXXXX
                BBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXX XX XX XXXXXXXXXXXXXXXXXX XXX XXXX XXXX XX XXX XXXXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXX XXX XXX XXX XX XXXX XXX XXXXXXX XXXXX XXXXXXXX XX XXXXXX X XXX XXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBX 
                       XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXX XXX
                    XXXX
                XXXXXX
                BBBBB
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXX
            X
        X
    X
    XXXXXX XXXXXXXXXXXX
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XX
        XXX
        
        XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXX XX XXXXX XXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXXXXXX
    X
X
XXXXXXXXX
BBBBBBBB

