BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        XXXX XXXXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXFFFFFXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXXXXXX
                BB BBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXXXXX
                BBBBB
            XXXXXX
            
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                
            XXXXX
            
            XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                
            XXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB B B
                XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFF XXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXX XXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXXX XXXX XXXXXX XXX
            BB BBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXXXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                BB BBBBBBBBBB
                XXXX XXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXX
                XXXXXX
                
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXX XXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXX
                BBBB
                XXXX XXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    BB BBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXX X X XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXXXBBBB BBBBBBBBBBBBBBBB BB BBBBBXXXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                    BBBBBBB
                    BBBBBBB
                    BBBBB
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    
                    XXXX XXXXXXXX XXXXXXXX XXX
                    BB BBB BBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBB BBBB BB BBBBBBBBBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
                
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX
                    XXXXXX XXX
                XXXXXXXXX
                
                BB BBB BBBBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                XXXXXXXXX
                BBBBB
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXX XXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXX XXXX XXXXXXXX XXX
            BB BBBBBBBBBBBBBBBBB
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFFFFFFFFXXXX
                                BBBBB
                                XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXFFFFFFF FF FFXXXXXXX
                                    XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXFFFFFFFFFF X FFFFFFFFFFXXXXXXX
                                    XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX X  XXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        BB BBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXX
                        XXXX
                        BBBB
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX XX XXXX
                        XXXXXXX
                        BBBBB
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXXXXX XXX
            BB BBBBBBB
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBB BB BBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBB
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFFFFFFFFXXXX
                                BBBBB
                                XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBB
                                    XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX
                                    BBBBB
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        BB BBBBBBBBBB
                        BB BBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX FFFFFFFFFFFFFXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBB
                            XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        BBBBB
                        XX XXXXXXBBB BBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBXXXXXX XXXXBBBBXXXX XXXXBBBBB
                        XXXX
                        BBBB
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX XX XXXXXX
                        XXXXXXX
                        BBBBB
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
            BB BBBBBBBBBBBBB
            XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX
                            XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXFFFFFFFFFFXXXX
                                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FF FFXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXXX XXXXX XXX
            BB BBB BBBBBBBBBBBBBBBBB BBB BBB BBBBBBB BBB BBB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXX XXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXFFFFFXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXX XXXXXXX XXX XXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBB B BB BBBBBBBBBBBBBBBBB
                            BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXXXXX XXXXXXXXXXXXX
                            BBBB
                                XX XXXXXXXXXX XXXXXXXXXXXXX
                            BBBBB
                        BBBBBB
                    XXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXX
XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX X X
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XX X
            XXXXXXXX XX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        X
        XXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        X
        XXXX X
            XXXXXXXX XX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        X
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX
        XXXXXXXXXXXX XXXXXXXX XXXXXXX
    X
XX
XX XXXX XXX XXXXX XXXX XX XX XXXXXXX XXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXX XXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXX X X
        XXXXXX XXXX
        XXXXXX XXXX
        XXXXXX XXXX
        XXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXX XXXX
    XX
    
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXXXX X
        XX XXXXX XXXXXXXX XXXXXXXX XX XXXX XXXXXXX XX XXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX
            
            XX XXXX XXXXXXX XX XXXXXXXX XXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                
                XX XXXXXX XXXX XXX XXXXXXXX XXXXXX X XXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                
                XX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXX XXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXX
                    XXX
                XXX
                
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                
                XX XXXXXX XXXXXXXX XX XXXXXXX XXXXXXXXXX XX XX XXXXXXXX XXXXXXX
                XXXXX XXXXXXXX X XXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXBBB BBBBBBBBBBBBBBXX X
                    XXXXXXX XXXXXXX
                    XXXXX XXXXXXXXX
                    XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    X
                XXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX
                XXX
            X
        XXX
    X
XXX

XX XXXXXX XX XXXXXX XXXXXXXX
XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXX XXXXXX XX XXXXXX XXXX XXXXXXXX XXX XXXXXXXXXXX
    XX XXXXXXXXXXXX X
        XXXXXXX
    X
    
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXX
            XXXXXXXXXXXX XXXXXXXXXXXXX
        XXX
        
        XX XXXXXXXXXXXXXX X
            XXXXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXX
            XXXXX XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXX XX XXXXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXX
            X
        X
    X
    XXXXXX XXXXXXXXXXXX
X

XX XXXXXXX XXXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXXXXX X
        XX XXXXXXX XXXXXX XXXXX XXXXXXX XXXX XX XXXXXXXXXX XXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXX XX XXXX X XXXXXX XXXXX XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXX XXXX XX XXXX XXXXXXX XXXX
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX XX XXXXXXXXX X
                    XXXXX XXXXXX X XXXXXXXXX
                    XX XXXXXX XXXXXXXXXX XXXXXXX XXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X
            XX XX XXX XXXXXX XXXXX XX XXXXX XXXXXX XXXXXX XXXXXXXX XXX
            XXXXXX XXXX
        X
        
        XX XXXX XXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXXX XXXXXXXXXX XXXXXXXXX
        XXX
        
        XX XXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX XX XXXX XXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XX XXXXXXX XXXXXXXXX
            XXX
        XXX
        
        XX XXXXX XX XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXXXXX XXX XXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            X
        XXX
        
        XX XXXXX XX XXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            X
        XXX
    X
XXX

XX XXXX XXXXX XXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X X
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                        XXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXX XXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX 
                                  XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
                                XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                        XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX 
                                XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXX XXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXX
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXX
    XXXXX XXXX X X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXX XX XXXXXXXX XXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXXXXXX
    X
X
XXXXXXXXX

XXXX XXXXXXX XXXXX XXXXX XXX
BB BBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XX X XXXXXXX XX XXX XXXXXX XXXXXXXX XXXXXX XX XXXXXX XXX XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB
BBBBBBBB

