BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        XXXX XXXXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXFFFFFXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXBBBBB XXXXXXXXXXX XXXXXXXX
                    BB BBBBBBBBBBBBBBBBBB BB BBBBBB
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    BBBB
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXXX
                BB BBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXXXXX
                BBBBB
            XXXXXX
            
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX
                
            XXXXX
            
            XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                
            XXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB B B
                XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFF XXXXXXXXXXXXX
                BBBBB
            XXXXXX
            
            XXXX XXXXXXX XXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                XXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        
        XXXX XXXXXXXXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                BB BBBBBBBBBB
                XXXX XXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFX XXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                XXXXXX
                
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXX XXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                XXXX
                BBBB
                XXXX XXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    BB BBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X X XXXX XXXXXXXXXXXXXXXXXXXXXXX X X XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBB BBBBBBBBBBBBBBBB BB BBBBBXXXBBBB BBBBBBBBBBBBBBBB BB BBBBBXXXBBBB BBBBBBBBBBBBBBBB BB BBBBBXBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                    BBBBBBB
                    BBBBBBB
                    BBBBB
                    XX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    
                    XXXX XXXXXXXX XXXXXXXX XXX
                    BB BBB BBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBB BBBB BB BBBBBBBBBBBBBBBB
                            XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
                
                XXXXXXX 
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX
                X
                    BB BBBBBBBBBBBBBBXXXXX XXXXXXXXBBBBXXXXXX XXXBBBBB
                    XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXX
                
                BB BBB BBBBBBBBBBBBBB
                XXXXXXX 
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                X
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                XXXXXXXXX
                BBBBB
                
                XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXX XXXXX XXXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXXX XX XXX XXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFF
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    BBB BBBBBB BB BBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                            BB BBBBBBBBBBBBBBBBBBB BB BBBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBB BBBBBBBBBBBBBBBBBBB BB BBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBB
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBBB
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            BBBBB
                        XXXXXX
                        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXXXXXXX XXXXXXX XXXXXX XXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXX XXX
    BB BBBBBBB
    XXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            BBB B BB BBBBBBBBBBBBBBBBB
                            BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            BBBB
                            XX XXXXXXXXXX XXXXXXXXXXXXX
                            BBBBB
                            BBBBBB
                        XXXXXX
                    XXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXXX XXXXXXX XXX
    BB BBBBBBBBBBBBBBB
    XXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFF X XXXXX
                XXXXXX
            XXXX
            BBBBBB
        XXXXXX
    XXXXXX
    BBBBB
XXXXXX

XXXX XXXXXXX XXXXX XXXXX XXX
BB BBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XX X XXXXXXX XX XXX XXXXXX XXXXXXXX XXXXXX XX XXXXXX XXX XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB

XXXXXXXX
XX XXXXXXX XXXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXXXXX X
        XX XXXXXXX XXXXXX XXXXX XXXXXXX XXXX XX XXXXXXXXXX XXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXX XX XXXX X XXXXXX XXXXX XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXX XXXX XX XXXX XXXXXXX XXXX
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXX XX XXXXXXXXX X
                    XXXXX XXXXXX X XXXXXXXXX
                    XX XXXXXX XXXXXXXXXX XXXXXXX XXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            X
            XX XX XXX XXXXXX XXXXX XX XXXXX XXXXXX XXXXXX XXXXXXXX XXX
            XXXXXX XXXX
        X
        
        XX XXXX XXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXXX XXXXXXXXXX XXXXXXXXX
        XXX
        
        XX XXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX XX XXXX XXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XX XXXXXXX XXXXXXXXX
            XXX
        XXX
        
        XX XXXXX XX XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXXXXX XXX XXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            X
        XXX
        
        XX XXXXX XX XXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX X XXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            X
        XXX
    X
XXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XX
            XX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XX
        XXX
        
        XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXX XX XXXXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXXXXXX
    X
X

XX XXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXX
XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX X X
    XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XX X
            XXXXXXXX XX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        X
        XXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
        X
        XXXX X
            XXXXXXXX XX
            XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        X
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX
        XXXXXXXXXXXX XXXXXXXX XXXXXXX
    X
XX
XX XXXX XXX XXXXX XXXX XX XX XXXXXXX XXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXX XXXXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXX X X
        XXXXXX XXXX
        XXXXXX XXXX
        XXXXXX XXXX
        XXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXX XXXX
    XX
    
    XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXXXX X
        XX XXXXX XXXXXXXX XXXXXXXX XX XXXX XXXXXXX XX XXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX
            
            XX XXXX XXXXXXX XX XXXXXXXX XXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                
                XX XXXXXX XXXX XXX XXXXXXXX XXXXXX X XXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                
                XX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXX XXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XX XXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXX
                    XXX
                XXX
                
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                
                XX XXXXXX XXXXXXXX XX XXXXXXX XXXXXXXXXX XX XX XXXXXXXX XXXXXXX
                XXXXX XXXXXXXX X XXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXBBB BBBBBBBBBBBBBBXX X
                    XXXXXXX XXXXXXX
                    XXXXX XXXXXXXXX
                    XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    X
                XXXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX
                XXX
            X
        XXX
    X
    
    XXXXXXXX XXXXXXXXXXXXXXX X
        XXX XXXXXXXXXXX X XXXXX
        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                    XXXXXX
                X
            X
        X
        XXXXXX XXXXXXXXXXXX
    X
XXX

XX XXXX XXXXX XXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXXX XXXXX XXXX
    XXXXX XXXXXXXXX X X
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
                        XXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXX XXXXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                               XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXX
                    XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX 
                                  XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXX XXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX 
                                XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXX
                        XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX 
                                XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXX XXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XX
    
    XX XXX XXXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    
    XX XXXXXX XXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXX X
        XXXXXXXXXXXXXXX
    X
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXX
    XXXXX XXXX X X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    
    XXX X
        XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXXXXXXXXXXXX
        XXX
        
        XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXX XX XXXXXXXX XXXXXXX
        X
    X XXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXX XXX XXXXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX
    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXX
            X
        X
    X
    XXXXXX XXXXXXXXXXXX
X
XXXXXXXXX
BBBBBBBB



