BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXX XXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXX FFFFFFFFF XX FFFFFFFFFXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX FFFFFFFFFXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFF XXXXX XXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBB
                XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX FFFFFFFFF BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BXXXBBBBXXXXBBBBB XXXXXXXXXX
            XXXXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXX XX XXX XXXXXXXXXXXX
            XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXX XXXXXXX
            XXXX
        XXXXXX
        BBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

