XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXXX
                BB BBBBBBBBBB
                XXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                XXXXXXX
                BBBBB
            XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BBBB
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            XXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXX
            XXXX
            BBBBB
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFF FF FFXXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFF X FFFFFFFFFF
            XXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
                XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 X  XXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    
                XXXX
                BBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXX
                BBBBB
            XXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     FFFFFFFFFFFFF
                XXXXXXX
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
    
    XXXX XXXXXXX XXXX X XXXX XXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
        XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
            FFFFFFFFFFFFFFFF
        XXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXXXX XXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB BB B
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXX XX XXXXXXXX XX X XXXX XXXXX XXXXXXXXX
        XXXXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBB
            BB BBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXX XXXXXXXXXXXXXX
            XXXX
            BBBB
            XXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                
            XXXXXX
            BBBBB
        BBBB
        XXXXXXX 
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX 
           XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX
        XXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
        BBBBB
    XXXXXX
XXXXXX

