BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'AI Placement Test') XXXXXXX
        XXXXXX
        
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX gettext(u'Find Your Starting Point') XXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXX
             gettext(u'Take a quick assessment to get personalized course recommendations tailored to your current level and goals.') 
        XXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Question 1 of 10') XXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Estimated time: 5-10 minutes') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'What is your primary learning goal?') XXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Career advancement') XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'I want to improve my skills for my current job or prepare for a new role') XXXXXX
                XXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Personal growth') XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u"I'm learning for personal interest and self-improvement") XXXXXX
                XXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Academic preparation') XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'I need to prepare for exams or academic requirements') XXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                 gettext(u'Previous') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                 gettext(u'Next Question') 
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

