BBBBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXXXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXXXXXXXX
                    XXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX
                    XXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXX XXXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        
        XXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXX
        XXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

