XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXX X X
            XXXXXX X
                XXXXXXX X
                    XXXXXXX X
                        XXXXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXXX
                    X
                X
            X
        X
    XXXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXX XXXXXX X
            XXXX X XXXXXXXX XX X
            XX X XXXXXXXX XX X
        X

        XXXXXXXXXX XXXXXXX X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXXX
            X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXX
            X
        X

        XXXXXXXXXX XXXXXXX X
            XX X XXXXXXXXXX XXXXXXXXXXXXXXXXXX X
            XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
        X

        XXXXXXXXXX XXXXXXXXXX X
            XXX XXXX X XXXXXXXX XXXX X
            XXX X XXXXXXXX XXXX X
        X

        XXXXXXXXXX XXXXXXXXX X
            XX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            X
            XXXX X
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            X
        X

        XX XXXXXXXXXX XXXX XXXXXXXX XX
        XXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX XXXXXXXX XXXXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXX
            XXXX XXXXX
            XXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX XX XXX XXXX
                XXXXXXXXX XXXX XXXX XXXXX XXX
                XXXXXXX XXXX XXX XXXX XXXX
                XXXXXXXXXXX XXX
            XX
            XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXX
            XXXXXXXX XX
        X

        XX XXXXXXXXX XXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX
                XXXXXXXXX XXXX XXXX XXXX XXX
                XXXXXXXXXXX XXX
            XX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXX
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
        X

        XX XXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
        X

        XX XXXXX XXXX XX
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXX 
                X XXXX XXXX XXXXXXX XX XX XXXXX
                X XXX XXXX XXXXXXX XX XX XXXXX
                XXXXX X XXX X XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X

        XX XXX XXXXXX XXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX
            XXXXXXXX XX
        X

        XX XXXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XX
            XXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXXXXXXX
                XXXXXXXXX XXXX XXXX XXXXXX
                XXXXXXXXXXX
            XX
            XXXXXXXXXX XXXXXXX XX XXXXXXXXX
            XXXXXXXXXXXXXXX XXXXX
        X

        XX XXXX XX
        XXXXXXXXXXX X
            XXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXX XXX XXXXXXX XX XX XXXXXX
            XXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXX XXXXX XXX XXXXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXX XX
            XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XX XXXX XX XXXXX XXXXXXXXX
        X

        XX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXX X
                XXXXXXXXXX XXXXX
                XXXXXXXX XX
                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            X
        X

        XX XXXX XXXXXX XX
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXX XXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXX XXXXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX X X X XXX XXXXXXXXX XXXX XXXX XXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X

        XX XXXXX XXXX XX
        XXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXX XXXXX
            XXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXX XXXXX XXXX XXXXX
            XXXXXXXX XX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X

        XX XXXXXX XXXXXX XX
        XXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XXXX XXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXX
        X

        XX XXXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXX
            XXXXXXX XXXXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXXXX XXXXXXXXX
            XXXX XXXX
            XXXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XX XXXXX XX
        XXXXXXXXXX X
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXXX XXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X

        XX XXXXXXXXXXXXX XXXXXXXX XX
        XXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX XXXX XXX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXX XXXX XXX XXXXX
            XXXXXX XXXXXXXX
        X

        XX XXXXX XXXXXXXXXX XX
        XXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXX
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXX X X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXXXXXX
        X

        XX XXXXXXXX XXXXXX XXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXX
            XXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXX X XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX 
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXXX XXXXX 
                        XXXXXXXXXXXXXXXXXX
                    XX
                XXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXX X XXXX XXXX XXXXXXXXXXX XXXXXXXX XXX
            BB BBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    BB BBBBBB BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBB BB BBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXBBBBXXXXXXXXXXXXXBBBBBXX
                        XX XXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBB BB BBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXBBBBBXXXXXX
                        XXXXXXXXXXXXX
                    XXXXXX
                    BBBBB
                BBBBBB
            XXXXXX
            BBBBB

            XXXX XXXXX XXXX XXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBBBBBBBB

                XXXX XXXXXXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX 
                        XXXXXXXXXXX 
                        XXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXX 
                        XXXXXXXX
                        XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX XX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXXXXX

                XXXX XXXXXXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX 
                        XXXXXXXXXXXXXXX 
                        XXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXX 
                        XXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                    XXXXXXX 
                        XXXXXXXXXXXXX 
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                    X
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX

                XXXX XXXXXXXX XX X XXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXXX 
                            XXXXXXXXXXXXXXX 
                            XXXXXXXXXXXXXXX 
                            XXXXXXXXXXXXXXXXXXXXXXX
                        X
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXXX
                    XX 
                        XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX 
                        XXXXXXXXXXXXXXXXX
                    X
                        XXXXXX XXXXXXXXX
                    XXXX
                XXXXXX

                XXXX XXXXXX XXXXXX XXX
                XXXXXXX 
                    XXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                X
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX

                XXXX XXXXX XXXXXXXXXX XXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXX

            XXXX XXXX XX XXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX XXXX XX XXXXXXXX
                    XX 
                        XXXXXXBBB BBBBBBBBX 
                        XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
                    X
                        XXXX XX XXXX
                    XXXX
                XXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                    XXXX XX XXXXXX
                    XX 
                        XXXXXXBBB BBBBBBBBBBBBBBBBX 
                        XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
                    X
                        XXXX XX XX X XXXXXXX
                    XXXX
                XXXX
            XXXXXX

            XXXX XXXX XX XXXX XXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XX 
                    XXXXXXBBB BBBBBBX 
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX
                X
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XX XXXXXXXXXXX
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXXXXXX
        XX XXXX XXX XXX XX XX XXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXXXX XXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    
                    XX XXXXXX XXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXX X XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                    X
                XXX
            X

            XX XXXX XXXXXXXXXX XXXX XXXXXXX XXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX X XXXXX
                XXX
            X

            XX XXXXXXXXXX XXXXX XXXXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
